#
# Copyright (c) 2011 NetApp, Inc.
# All rights reserved.
#
# *** Generated: Thu Aug 25 11:31:46 2011
#

# Contains DataFabric Manager server API error code constants.
package DfmErrno;
use strict;
use vars('@ISA','@EXPORT');
require Exporter;
@ISA = qw(Exporter);
@EXPORT = qw(
	EHOSTDOESNOTEXIST
	EINVALIDTAG
	ENAMENOTFOUND
	EVIEWEXISTS
	EUNKNOWNFAILOVERCONFIG
	ECANTREADCONFIGFILE
	ECANTWRITECONFIGFILE
	EBADCREDENTIALS
	ECANTREADSTATUSFILE
	ENOTCUSTOMEVENTCLASS
	EEVENTGENERATEFAILED
	EINVALIDINPUT
	EEVENTCLASSEXISTS
	ENOSUCHEVENTCLASS
	EXMLVALIDATEFAIL
	ESCRIPTJOBRUNNING
	EZIPFILEERROR
	EZIPFILEEXTRACTERROR
	ESCRIPTPERMERROR
	EDIRDOESNOTEXIST
	EDIRNOTWRITABLE
	EFILEDOESNOTEXIST
	EDELETEFAILED
	EABORTINPROGRESS
	ENOBACKUPINPROGRESS
	EPROCESSKILLFAILED
	EINVALIDROLENAME
	EDUPLICATEROLE
	EINVALIDDESCRIPTION
	ENOTFOUNDROLE
	EROLEASSIGNED
	EINVALIDOPERATIONNAME
	EINVALIDAPPLICATIONNAME
	EINVALIDOPERATIONTYPE
	EINVALIDLONGDESC
	EINVALIDSHORTDESC
	EINVALIDRESOURCETYPE
	EDUPOPERATION
	ENOTFOUNDOPERATION
	EINVALIDRESOURCE
	ENOTASSIGNEDROLE
	ENOTASSIGNEDCAPABILITY
	EDUPCAPABILITY
	ENOTINHERITEDROLE
	EINVALIDUSERNAME
	ENOTFOUNDUSER
	EROLEISPERMANENT
	ESCHEDULEINVALIDINPUT
	ESCHEDULENOTFOUND
	ESCHEDULEDUPLICATE
	ESCHEDULEINUSE
	ERESOURCEPOOLDOESNOTEXIST
	ERESOURCEPOOLEXISTS
	EOBJECTINANOTHERDYNAMICREFERENCE
	EOBJECTNOTINRESOURCEPOOL
	EOBJECTEXISTSINRESOURCEPOOL
	ERESOURCEPOOLNOTEMPTY
	ERESOURCEPOOLINUSE
	EOBJECTAMBIGUOUS
	EDATASETEXISTS
	ETHROTTLENOTFOUND
	ETHROTTLEDUPLICATE
	ETHROTTLEINUSE
	ETHROTTLEINVALIDINPUT
	EJOBDOESNOTEXIST
	EJOBALREADYCOMPLETED
	EJOBALREADYABORTED
	EJOBCANNOTBEABORTED
	EEDITINPROGRESS
	EDPPOLICYNODENOTFOUND
	EDPPOLICYNOTFOUND
	EQTREEDOESNOTEXIST
	EINVALIDQTREENAME
	EQTREEALREADYEXISTS
	EINVALIDEMAILADDR
	EGROUPDOESNOTEXIST
	ERUNASUNSUPPORTED
	EINVALIDTRAPADDR
	EINVALIDALARMTIME
	EINVALIDEVENTCLASSEXP
	EALARMDOESNOTEXIST
	EQTREEMANAGEDBYAPP
	EQTREEUNDELETEFAIL
	EQTREEDELETEDPARENT
	EQTREEMONITORONFAIL
	EQTREEMONITOROFFFAIL
	EDATASETNOTEMPTY
	EEDITSESSIONNOTFOUND
	EALREADYINDATASET
	ENOTINDATASET
	EEDITSESSIONINPROGRESS
	ENOTINGROUP
	EDATASETNODEISROOT
	ESTORAGESETNOTEMPTY
	EINVALIDSTORAGESETMAP
	EROOTSTORAGESET
	EPOLICYNOTMODIFIABLE
	EPOLICYTOPOLOGYCHANGED
	EINVALIDPOLICYPROPERTY
	EOBJECTNOTFOUND
	EACCESSDENIED
	ENOSUCHEVENT
	EALREADYACKWED
	EDATABASEERROR
	EINVALIDEVENTSEVERITY
	EPOLICYEXISTS
	EINVALIDMEMBERTYPE
	EEDITSESSIONOBJECTALREADYLOCKED
	EEDITSESSIONCONFLICTINGOP
	EBADHOSTTYPE
	EPARENTGROUPNAMEAMBIGUOUS
	EMEMBERNOTINGROUP
	EMEMBERALREADYINGROUP
	EINVALIDMEMBER
	EMEMBERNAMEAMBIGUOUS
	EGROUPCOPYERROR
	EGROUPMOVEERROR
	EGROUPEXISTS
	EINVALIDGROUPNAME
	EPARENTGROUPDOESNOTEXIST
	EALARMTESTFAILED
	EBACKUPDOESNOTEXIST
	EDPPOLICYINUSE
	ESTORAGESETNOTINDATASET
	EOBJECTEXISTS
	ELICENSEINUSE
	ESCHEDULENOTMODIFIABLE
	ETHROTTLENOTMODIFIABLE
	EOSSVCANTTAKESNAPSHOTS
	EOPERATIONISPERMANENT
	EBACKUPLOCATIONDOESNOTEXIST
	EPATHDOESNOTEXIST
	EDUPLICATEROLEREF
	EDSCONFLICTALREADYINDATASET
	EDSCONFLICTALREADYINRESPOOL
	EDSCONFLICTCANTMIRROROSSV
	EDSCONFLICTCANTSNAPSHOTOSSV
	EDSCONFLICTNOSMLICENSE
	EDSCONFLICTNOSMSVLICENSE
	EDSCONFLICTROOTNODE
	EDSCONFLICTNOTROOTNODE
	EDSCONFLICTNOTLEAFNODE
	EINVALIDLICENSE
	EHOSTCOMMUNICATION
	EHOSTACCESSDENIED
	EHOSTREQUESTDENIED
	EHOSTEXISTS
	EHOSTADDNOCONTACT
	EHOSTADDNOTRESOLVED
	EHOSTADDDUPPRODID
	EHOSTADDTAKENOVER
	EHOSTADDNOFCSWITCH
	EHOSTADDVFILERPARENTDELETED
	EHOSTRUNMONFAILED
	ESERVICESTATEUNKNOWN
	EAGENTNOTUPTODATE
	EHOSTADDNOLICENSE
	EHOSTADDNOTENABLED
	EHOSTADDNONODES
	EHOSTADDMISMATCHPRODID
	EHOSTNDMPACCESSFAILED
	EHOSTBADCONFIG
	EHOSTINUSE
	EHOSTVFILERADDFAILED
	EHOSTNDMPTABLOOKUPFAILED
	EOPERATIONTIMEDOUT
	EDSCONFLICTINCOMPATIBLEPOLICY
	EDSCONFLICTOSSVNOTALLOWED
	EHOSTRSHACCESSFAILED
	ECOMMENTFIELDALREADYEXISTS
	ECOMMENTFIELDDOESNOTEXIST
	ESYSTEMCOMMENTFIELD
	EHOSTOSVERSIONNOTSUPPORTED
	EROLEAMBIGUOUS
	EINVALIDCAPABILITY
	EUSERGROUPNOTFOUND
	EUSERGROUPAMBIGUOUS
	EUSERAMBIGUOUS
	EDUPLICATEUSER
	EINVALIDUSERFULLNAME
	EPASSWORDAGENOTSUPPORTED
	EINVALIDPASSWORDAGE
	EPERFUPDATEDISABLED
	ENOFAVORITES
	ENORECENTVIEWED
	ETHRESHOLDEXIST
	EREPORTAMBIGUOUS
	EREPORTSCHEDULEDUPLICATE
	EREPORTOUTPUTNOTFOUND
	EINVALIDUSERGROUPNAME
	EDUPLICATEUSERGROUP
	EDOMAINUSERNOTFOUND
	EDOMAINUSERAMBIGUOUS
	EINVALIDDOMAINUSERNAME
	EREPORTNOTFOUND
	EREPORTOUTPUTDELETEERROR
	EREPORTOUTPUTFILEREADERROR
	EREPORTSCHEDULEDELETEERROR
	ENOPERFTHRESHOLDVIEWEXISTS
	EINCOMPATIBLEROLE
	EINCOMPATIBLEUSERGROUP
	EREPORTOUTPUTFILENOTFOUND
	EREPORTNOTLICENSED
	EREPORTNOTSCHEDULABLE
	EINVALIDOBJECTTYPE
	ESNAPSHOTNOTFOUND
	EPROVPOLICYINUSE
	EGRAPHNOTFOUND
	EDSCONFLICTPROVPOLICYNOTALLOWED
	EVFILERTEMPLATEEXISTS
	EDSCONFLICTINVALIDVFILER
	EFILERNOTFOUND
	EMULTISTORENOTLICENSED
	ECANNOTDESTROYSTORAGE
	EDSCONFLICTMEMBERVFILERMISMATCH
	EDATASETWRONGDRSTATE
	EDATASETDRSTATEUNCHANGED
	EDATASETFAILOVERNOTREADY
	EDSCONFLICTCANTFAILOVEROSSV
	EDSCONFLICTNOSVLICENSE
	EDSCONFLICTOSVERSIONNOTCOMPATIBLE
	EDSCONFLICTNDRESTORE
	ENDRESTORENOTPOSSIBLE
	EDATASETNOTDRCAPABLE
	EDATASETNOTINFAILEDOVERSTATE
	EBACKUPBUSY
	EDATASETNOTEFFECTIVEPRIMARY
	EDATASETNOTINSTABLEDRSTATE
	ENODENOTDRCAPABLE
	EDRLICENSEREQUIRED
	EJOBCANNOTBESTORED
	EDATASETFAILINGOVER
	EPERFTEMPLATEEXISTS
	EDSCONFLICTWITHANOTHERDATASET
	EOBJECTINDIRECTMEMOFANOTHERDYNAMICREF
	EDSCONFLICTTRANSPARENTMIGRATION
	EDEDUPENOTSUPPORTED
	EUNDEDUPENOTSUPPORTED
	EDEDUPEABORTNOTSUPPORTED
	EDSCONFLICTDEDUPLICATION
	EDEDUPEALREADYRUNNING
	EDEDUPENOTRUNNING
	EINVALIDMIGRATIONSTATUS
	EMIGRATEDESTINATIONSELECTIONFAILED
	EMIGRATENOTSUPPORTED
	EDATASETMIGRATING
	EINVALIDJOBTYPE
	EINVALIDJOBSTATE
	EOPERATIONNOTSUPPORTED
	EDSCONFLICTSRCDESTINSAMEAGGR
	ESERVICEEXISTS
	ESTORAGESERVICEINUSE
	ESERVICEISATTACHED
	EPROVISIONFAILED
	EVFILERTEMPLATEINUSE
	EVFILERINTERFACENOTSET
	EONLINENOTPOSSIBLE
	ECLIENTSTATSCOLLECTIONINPROGRESS
	EPERFEXPORTINPROGRESS
	ESPACEMGMTSESSIONINPROGRESS
	ESPACEMGMTSESSIONNOTFOUND
	ESPACEMGMTCONFLICTOP
	ESPCMGMTNOSUCHOP
	EDATASETBUSY
	EAPPPOLICYINUSE
	EDSCONFLICTINCOMPATIBLEOBJTYPE
	EDSCONFLICTRPNOTALLOWED
	EDSCONFLICTALREADYEXCLUDED
	EDSCONFLICTNOTEXCLUDED
	EHS_UNREGISTER_ERROR
	EHS_REGISTER_ERROR
	EINVALIDGROUPFILTER
	EINVALIDOPTION
	ECANNOTDELETECLUSTERNODEHOST
	EREPORTCATEGORYNOTFOUND
	EUNUSEDAPPLICATIONOBJECTSETTING
	EAPPPOLICYNOTFOUND
	EOBJECTNOTRESTORABLE
	EOBJECTNOTFOUNDINBACKUP
	EMAXBACKUPMOUNT
	EBACKUP_ALREADY_MOUNTED
	EBACKUP_NOT_MOUNTED
	EHS_ALREADY_AUTHORIZED
	EHSNOTAUTHORIZED
	EHS_CONFIGURE_FAILED
	ESTORAGE_MAP_NOT_FOUND
);

use constant EHOSTDOESNOTEXIST => 21001;
use constant EINVALIDTAG => 21002;
use constant ENAMENOTFOUND => 21003;
use constant EVIEWEXISTS => 21004;
use constant EUNKNOWNFAILOVERCONFIG => 21005;
use constant ECANTREADCONFIGFILE => 21006;
use constant ECANTWRITECONFIGFILE => 21007;
use constant EBADCREDENTIALS => 21008;
use constant ECANTREADSTATUSFILE => 21009;
use constant ENOTCUSTOMEVENTCLASS => 21010;
use constant EEVENTGENERATEFAILED => 21011;
use constant EINVALIDINPUT => 21012;
use constant EEVENTCLASSEXISTS => 21013;
use constant ENOSUCHEVENTCLASS => 21014;
use constant EXMLVALIDATEFAIL => 21015;
use constant ESCRIPTJOBRUNNING => 21016;
use constant EZIPFILEERROR => 21017;
use constant EZIPFILEEXTRACTERROR => 21018;
use constant ESCRIPTPERMERROR => 21019;
use constant EDIRDOESNOTEXIST => 21020;
use constant EDIRNOTWRITABLE => 21021;
use constant EFILEDOESNOTEXIST => 21022;
use constant EDELETEFAILED => 21023;
use constant EABORTINPROGRESS => 21024;
use constant ENOBACKUPINPROGRESS => 21025;
use constant EPROCESSKILLFAILED => 21026;
use constant EINVALIDROLENAME => 21027;
use constant EDUPLICATEROLE => 21028;
use constant EINVALIDDESCRIPTION => 21029;
use constant ENOTFOUNDROLE => 21030;
use constant EROLEASSIGNED => 21031;
use constant EINVALIDOPERATIONNAME => 21032;
use constant EINVALIDAPPLICATIONNAME => 21033;
use constant EINVALIDOPERATIONTYPE => 21034;
use constant EINVALIDLONGDESC => 21036;
use constant EINVALIDSHORTDESC => 21037;
use constant EINVALIDRESOURCETYPE => 21038;
use constant EDUPOPERATION => 21039;
use constant ENOTFOUNDOPERATION => 21040;
use constant EINVALIDRESOURCE => 21041;
use constant ENOTASSIGNEDROLE => 21042;
use constant ENOTASSIGNEDCAPABILITY => 21043;
use constant EDUPCAPABILITY => 21044;
use constant ENOTINHERITEDROLE => 21045;
use constant EINVALIDUSERNAME => 21046;
use constant ENOTFOUNDUSER => 21047;
use constant EROLEISPERMANENT => 21048;
use constant ESCHEDULEINVALIDINPUT => 22200;
use constant ESCHEDULENOTFOUND => 22201;
use constant ESCHEDULEDUPLICATE => 22202;
use constant ESCHEDULEINUSE => 22203;
use constant ERESOURCEPOOLDOESNOTEXIST => 22204;
use constant ERESOURCEPOOLEXISTS => 22205;
use constant EOBJECTINANOTHERDYNAMICREFERENCE => 22206;
use constant EOBJECTNOTINRESOURCEPOOL => 22207;
use constant EOBJECTEXISTSINRESOURCEPOOL => 22208;
use constant ERESOURCEPOOLNOTEMPTY => 22209;
use constant ERESOURCEPOOLINUSE => 22210;
use constant EOBJECTAMBIGUOUS => 22211;
use constant EDATASETEXISTS => 22212;
use constant ETHROTTLENOTFOUND => 22213;
use constant ETHROTTLEDUPLICATE => 22214;
use constant ETHROTTLEINUSE => 22215;
use constant ETHROTTLEINVALIDINPUT => 22216;
use constant EJOBDOESNOTEXIST => 22217;
use constant EJOBALREADYCOMPLETED => 22218;
use constant EJOBALREADYABORTED => 22219;
use constant EJOBCANNOTBEABORTED => 22220;
use constant EEDITINPROGRESS => 22221;
use constant EDPPOLICYNODENOTFOUND => 22222;
use constant EDPPOLICYNOTFOUND => 22223;
use constant EQTREEDOESNOTEXIST => 22224;
use constant EINVALIDQTREENAME => 22225;
use constant EQTREEALREADYEXISTS => 22226;
use constant EINVALIDEMAILADDR => 22227;
use constant EGROUPDOESNOTEXIST => 22228;
use constant ERUNASUNSUPPORTED => 22229;
use constant EINVALIDTRAPADDR => 22230;
use constant EINVALIDALARMTIME => 22231;
use constant EINVALIDEVENTCLASSEXP => 22232;
use constant EALARMDOESNOTEXIST => 22233;
use constant EQTREEMANAGEDBYAPP => 22234;
use constant EQTREEUNDELETEFAIL => 22235;
use constant EQTREEDELETEDPARENT => 22236;
use constant EQTREEMONITORONFAIL => 22237;
use constant EQTREEMONITOROFFFAIL => 22238;
use constant EDATASETNOTEMPTY => 22239;
use constant EEDITSESSIONNOTFOUND => 22240;
use constant EALREADYINDATASET => 22241;
use constant ENOTINDATASET => 22242;
use constant EEDITSESSIONINPROGRESS => 22243;
use constant ENOTINGROUP => 22245;
use constant EDATASETNODEISROOT => 22246;
use constant ESTORAGESETNOTEMPTY => 22247;
use constant EINVALIDSTORAGESETMAP => 22248;
use constant EROOTSTORAGESET => 22249;
use constant EPOLICYNOTMODIFIABLE => 22251;
use constant EPOLICYTOPOLOGYCHANGED => 22252;
use constant EINVALIDPOLICYPROPERTY => 22253;
use constant EOBJECTNOTFOUND => 22255;
use constant EACCESSDENIED => 22256;
use constant ENOSUCHEVENT => 22257;
use constant EALREADYACKWED => 22258;
use constant EDATABASEERROR => 22259;
use constant EINVALIDEVENTSEVERITY => 22260;
use constant EPOLICYEXISTS => 22261;
use constant EINVALIDMEMBERTYPE => 22262;
use constant EEDITSESSIONOBJECTALREADYLOCKED => 22263;
use constant EEDITSESSIONCONFLICTINGOP => 22264;
use constant EBADHOSTTYPE => 22265;
use constant EPARENTGROUPNAMEAMBIGUOUS => 22267;
use constant EMEMBERNOTINGROUP => 22268;
use constant EMEMBERALREADYINGROUP => 22269;
use constant EINVALIDMEMBER => 22270;
use constant EMEMBERNAMEAMBIGUOUS => 22271;
use constant EGROUPCOPYERROR => 22272;
use constant EGROUPMOVEERROR => 22273;
use constant EGROUPEXISTS => 22274;
use constant EINVALIDGROUPNAME => 22275;
use constant EPARENTGROUPDOESNOTEXIST => 22276;
use constant EALARMTESTFAILED => 22280;
use constant EBACKUPDOESNOTEXIST => 22281;
use constant EDPPOLICYINUSE => 22282;
use constant ESTORAGESETNOTINDATASET => 22283;
use constant EOBJECTEXISTS => 22284;
use constant ELICENSEINUSE => 22285;
use constant ESCHEDULENOTMODIFIABLE => 22286;
use constant ETHROTTLENOTMODIFIABLE => 22287;
use constant EOSSVCANTTAKESNAPSHOTS => 22288;
use constant EOPERATIONISPERMANENT => 22289;
use constant EBACKUPLOCATIONDOESNOTEXIST => 22290;
use constant EPATHDOESNOTEXIST => 22291;
use constant EDUPLICATEROLEREF => 22292;
use constant EDSCONFLICTALREADYINDATASET => 22293;
use constant EDSCONFLICTALREADYINRESPOOL => 22294;
use constant EDSCONFLICTCANTMIRROROSSV => 22295;
use constant EDSCONFLICTCANTSNAPSHOTOSSV => 22296;
use constant EDSCONFLICTNOSMLICENSE => 22297;
use constant EDSCONFLICTNOSMSVLICENSE => 22298;
use constant EDSCONFLICTROOTNODE => 22299;
use constant EDSCONFLICTNOTROOTNODE => 22300;
use constant EDSCONFLICTNOTLEAFNODE => 22301;
use constant EINVALIDLICENSE => 22302;
use constant EHOSTCOMMUNICATION => 22308;
use constant EHOSTACCESSDENIED => 22309;
use constant EHOSTREQUESTDENIED => 22310;
use constant EHOSTEXISTS => 22311;
use constant EHOSTADDNOCONTACT => 22312;
use constant EHOSTADDNOTRESOLVED => 22313;
use constant EHOSTADDDUPPRODID => 22314;
use constant EHOSTADDTAKENOVER => 22315;
use constant EHOSTADDNOFCSWITCH => 22316;
use constant EHOSTADDVFILERPARENTDELETED => 22317;
use constant EHOSTRUNMONFAILED => 22319;
use constant ESERVICESTATEUNKNOWN => 22320;
use constant EAGENTNOTUPTODATE => 22321;
use constant EHOSTADDNOLICENSE => 22322;
use constant EHOSTADDNOTENABLED => 22323;
use constant EHOSTADDNONODES => 22324;
use constant EHOSTADDMISMATCHPRODID => 22325;
use constant EHOSTNDMPACCESSFAILED => 22327;
use constant EHOSTBADCONFIG => 22328;
use constant EHOSTINUSE => 22329;
use constant EHOSTVFILERADDFAILED => 22330;
use constant EHOSTNDMPTABLOOKUPFAILED => 22331;
use constant EOPERATIONTIMEDOUT => 22333;
use constant EDSCONFLICTINCOMPATIBLEPOLICY => 22334;
use constant EDSCONFLICTOSSVNOTALLOWED => 22335;
use constant EHOSTRSHACCESSFAILED => 22336;
use constant ECOMMENTFIELDALREADYEXISTS => 23301;
use constant ECOMMENTFIELDDOESNOTEXIST => 23302;
use constant ESYSTEMCOMMENTFIELD => 23303;
use constant EHOSTOSVERSIONNOTSUPPORTED => 23304;
use constant EROLEAMBIGUOUS => 23305;
use constant EINVALIDCAPABILITY => 23306;
use constant EUSERGROUPNOTFOUND => 23307;
use constant EUSERGROUPAMBIGUOUS => 23308;
use constant EUSERAMBIGUOUS => 23309;
use constant EDUPLICATEUSER => 23310;
use constant EINVALIDUSERFULLNAME => 23311;
use constant EPASSWORDAGENOTSUPPORTED => 23312;
use constant EINVALIDPASSWORDAGE => 23313;
use constant EPERFUPDATEDISABLED => 23314;
use constant ENOFAVORITES => 23315;
use constant ENORECENTVIEWED => 23316;
use constant ETHRESHOLDEXIST => 23317;
use constant EREPORTAMBIGUOUS => 23318;
use constant EREPORTSCHEDULEDUPLICATE => 23319;
use constant EREPORTOUTPUTNOTFOUND => 23320;
use constant EINVALIDUSERGROUPNAME => 23321;
use constant EDUPLICATEUSERGROUP => 23322;
use constant EDOMAINUSERNOTFOUND => 23323;
use constant EDOMAINUSERAMBIGUOUS => 23324;
use constant EINVALIDDOMAINUSERNAME => 23325;
use constant EREPORTNOTFOUND => 23326;
use constant EREPORTOUTPUTDELETEERROR => 23327;
use constant EREPORTOUTPUTFILEREADERROR => 23328;
use constant EREPORTSCHEDULEDELETEERROR => 23329;
use constant ENOPERFTHRESHOLDVIEWEXISTS => 23330;
use constant EINCOMPATIBLEROLE => 23331;
use constant EINCOMPATIBLEUSERGROUP => 23332;
use constant EREPORTOUTPUTFILENOTFOUND => 23333;
use constant EREPORTNOTLICENSED => 23334;
use constant EREPORTNOTSCHEDULABLE => 23335;
use constant EINVALIDOBJECTTYPE => 23336;
use constant ESNAPSHOTNOTFOUND => 23337;
use constant EPROVPOLICYINUSE => 23338;
use constant EGRAPHNOTFOUND => 23339;
use constant EDSCONFLICTPROVPOLICYNOTALLOWED => 23340;
use constant EVFILERTEMPLATEEXISTS => 23341;
use constant EDSCONFLICTINVALIDVFILER => 23342;
use constant EFILERNOTFOUND => 23343;
use constant EMULTISTORENOTLICENSED => 23344;
use constant ECANNOTDESTROYSTORAGE => 23345;
use constant EDSCONFLICTMEMBERVFILERMISMATCH => 23346;
use constant EDATASETWRONGDRSTATE => 23400;
use constant EDATASETDRSTATEUNCHANGED => 23401;
use constant EDATASETFAILOVERNOTREADY => 23402;
use constant EDSCONFLICTCANTFAILOVEROSSV => 23403;
use constant EDSCONFLICTNOSVLICENSE => 23404;
use constant EDSCONFLICTOSVERSIONNOTCOMPATIBLE => 23405;
use constant EDSCONFLICTNDRESTORE => 23406;
use constant ENDRESTORENOTPOSSIBLE => 23407;
use constant EDATASETNOTDRCAPABLE => 23408;
use constant EDATASETNOTINFAILEDOVERSTATE => 23409;
use constant EBACKUPBUSY => 23410;
use constant EDATASETNOTEFFECTIVEPRIMARY => 23411;
use constant EDATASETNOTINSTABLEDRSTATE => 23412;
use constant ENODENOTDRCAPABLE => 23413;
use constant EDRLICENSEREQUIRED => 23414;
use constant EJOBCANNOTBESTORED => 23415;
use constant EDATASETFAILINGOVER => 23416;
use constant EPERFTEMPLATEEXISTS => 23417;
use constant EDSCONFLICTWITHANOTHERDATASET => 23418;
use constant EOBJECTINDIRECTMEMOFANOTHERDYNAMICREF => 23419;
use constant EDSCONFLICTTRANSPARENTMIGRATION => 23500;
use constant EDEDUPENOTSUPPORTED => 23501;
use constant EUNDEDUPENOTSUPPORTED => 23502;
use constant EDEDUPEABORTNOTSUPPORTED => 23503;
use constant EDSCONFLICTDEDUPLICATION => 23504;
use constant EDEDUPEALREADYRUNNING => 23505;
use constant EDEDUPENOTRUNNING => 23506;
use constant EINVALIDMIGRATIONSTATUS => 23507;
use constant EMIGRATEDESTINATIONSELECTIONFAILED => 23508;
use constant EMIGRATENOTSUPPORTED => 23509;
use constant EDATASETMIGRATING => 23510;
use constant EINVALIDJOBTYPE => 23511;
use constant EINVALIDJOBSTATE => 23512;
use constant EOPERATIONNOTSUPPORTED => 23513;
use constant EDSCONFLICTSRCDESTINSAMEAGGR => 23514;
use constant ESERVICEEXISTS => 23515;
use constant ESTORAGESERVICEINUSE => 23516;
use constant ESERVICEISATTACHED => 23517;
use constant EPROVISIONFAILED => 23518;
use constant EVFILERTEMPLATEINUSE => 23519;
use constant EVFILERINTERFACENOTSET => 23520;
use constant EONLINENOTPOSSIBLE => 23521;
use constant ECLIENTSTATSCOLLECTIONINPROGRESS => 23522;
use constant EPERFEXPORTINPROGRESS => 23701;
use constant ESPACEMGMTSESSIONINPROGRESS => 23801;
use constant ESPACEMGMTSESSIONNOTFOUND => 23802;
use constant ESPACEMGMTCONFLICTOP => 23803;
use constant ESPCMGMTNOSUCHOP => 23804;
use constant EDATASETBUSY => 23805;
use constant EAPPPOLICYINUSE => 23806;
use constant EDSCONFLICTINCOMPATIBLEOBJTYPE => 23807;
use constant EDSCONFLICTRPNOTALLOWED => 23808;
use constant EDSCONFLICTALREADYEXCLUDED => 23809;
use constant EDSCONFLICTNOTEXCLUDED => 23810;
use constant EHS_UNREGISTER_ERROR => 23811;
use constant EHS_REGISTER_ERROR => 23812;
use constant EINVALIDGROUPFILTER => 23813;
use constant EINVALIDOPTION => 23814;
use constant ECANNOTDELETECLUSTERNODEHOST => 23815;
use constant EREPORTCATEGORYNOTFOUND => 23816;
use constant EUNUSEDAPPLICATIONOBJECTSETTING => 23820;
use constant EAPPPOLICYNOTFOUND => 23821;
use constant EOBJECTNOTRESTORABLE => 23822;
use constant EOBJECTNOTFOUNDINBACKUP => 23823;
use constant EMAXBACKUPMOUNT => 23824;
use constant EBACKUP_ALREADY_MOUNTED => 23825;
use constant EBACKUP_NOT_MOUNTED => 23826;
use constant EHS_ALREADY_AUTHORIZED => 23827;
use constant EHSNOTAUTHORIZED => 23828;
use constant EHS_CONFIGURE_FAILED => 23829;
use constant ESTORAGE_MAP_NOT_FOUND => 23831;

1;
