#
# Copyright (c) 2011 NetApp, Inc.
# All rights reserved.
#
# *** Generated: Thu Aug 25 17:03:16 2011
#

package NaErrno;
use strict;
use vars('@ISA','@EXPORT');
require Exporter;
@ISA = qw(Exporter);
@EXPORT = qw(
	EONTAPI_EPERM
	EONTAPI_ENOENT
	EONTAPI_ESRCH
	EONTAPI_EINTR
	EONTAPI_EIO
	EONTAPI_ENXIO
	EONTAPI_E2BIG
	EONTAPI_ENOEXEC
	EONTAPI_EBADF
	EONTAPI_ECHILD
	EONTAPI_EDEADLK
	EONTAPI_ENOMEM
	EONTAPI_EACCES
	EONTAPI_EFAULT
	EONTAPI_ENOTBLK
	EONTAPI_EBUSY
	EONTAPI_EEXIST
	EONTAPI_EXDEV
	EONTAPI_ENODEV
	EONTAPI_ENOTDIR
	EONTAPI_EISDIR
	EONTAPI_EINVAL
	EONTAPI_ENFILE
	EONTAPI_EMFILE
	EONTAPI_ENOTTY
	EONTAPI_ETXTBSY
	EONTAPI_EFBIG
	EONTAPI_ENOSPC
	EONTAPI_ESPIPE
	EONTAPI_EROFS
	EONTAPI_EMLINK
	EONTAPI_EPIPE
	EONTAPI_EDOM
	EONTAPI_ERANGE
	EONTAPI_EAGAIN
	EONTAPI_EINPROGESS
	EONTAPI_EALREADY
	EONTAPI_ENOTSOCK
	EONTAPI_EDESTADDRREQ
	EONTAPI_EMSGSIZE
	EONTAPI_EPROTOTYPE
	EONTAPI_ENOPROTOOPT
	EONTAPI_EPROTONOSUPPORT
	EONTAPI_ESOCKTNOSUPPORT
	EONTAPI_EOPNOTSUPP
	EONTAPI_EPFNOSUPPORT
	EONTAPI_EAFNOSUPPORT
	EONTAPI_EADDRINUSE
	EONTAPI_EADDRNOTAVAIL
	EONTAPI_ENETDOWN
	EONTAPI_ENETUNREACH
	EONTAPI_ENETRESET
	EONTAPI_ECONNABORTED
	EONTAPI_ECONNRESET
	EONTAPI_ENOBUFS
	EONTAPI_EISCONN
	EONTAPI_ENOTCONN
	EONTAPI_ESHUTDOWN
	EONTAPI_ETOOMANYREFS
	EONTAPI_ETIMEDOUT
	EONTAPI_ECONNREFUSED
	EONTAPI_ELOOP
	EONTAPI_ENAMETOOLONG
	EONTAPI_EHOSTDOWN
	EONTAPI_EHOSTUNREACH
	EONTAPI_ENOTEMPTY
	EONTAPI_EPROCLIM
	EONTAPI_EUSERS
	EONTAPI_EDQUOT
	EONTAPI_ESTALE
	EONTAPI_EREMOTE
	EONTAPI_EBADRPC
	EONTAPI_ERPCMSGDENIED
	EONTAPI_EPROGUNAVAIL
	EONTAPI_EPROGMISMATCH
	EONTAPI_EPROCUNAVAIL
	EONTAPI_ENOLCK
	EONTAPI_ENOSYS
	EONTAPI_EFTYPE
	EONTAPI_EMTUTOOBIG
	EONTAPI_EOFFLINE
	EONTAPI_EBADSTREAM
	EONTAPI_EBADSTREAMDIR
	EONTAPI_ELOADCOMPLETE
	EONTAPI_EMOUNTING
	EONTAPI_EWFLUSH
	EONTAPI_EBADPATH
	EONTAPI_EBADCHAR
	EONTAPI_ESHARECONFLICT
	EONTAPI_ELOCKCONFLICT
	EONTAPI_ENOTCOVERED
	EONTAPI_EBADXINODE
	EONTAPI_ENOTXINODE
	EONTAPI_EBADOWNER
	EONTAPI_ERMTWRITELEN
	EONTAPI_EBADRMT
	EONTAPI_EKNOWNBADRMT
	EONTAPI_ERMTEOF
	EONTAPI_EDELPENDING
	EONTAPI_ETRUNCATED
	EONTAPI_EREJECTED
	EONTAPI_EREADONLY
	EONTAPI_EPARTNERREJECT
	EONTAPI_ETOOCOMPLEX
	EONTAPI_EREGX
	EONTAPI_EREGXBADVALUE
	EONTAPI_EPERSISTENCE
	EONTAPI_ESTHREAD
	EONTAPI_EDISABLED
	EONTAPI_ENOTVSCANNED
	EONTAPI_EFABRIC
	EONTAPI_ESYSTEMERR
	EONTAPI_EGSSAPI
	EONTAPI_ERPCGSSSEQNUM
	EONTAPI_EPROXYME
	EONTAPI_ERSRVCONFLICT
	EONTAPI_ERSRVNSUPPORTED
	EONTAPI_ENOQTREE
	EONTAPI_ENOTLOCKED
	EONTAPI_ELOCKCANCELLED
	EONTAPI_ENOSPCSNAP
	EONTAPI_ENOMORESNAPS
	EONTAPI_ERECURSE
	EONTAPI_ERECLAIM
	EONTAPI_EZEROLENREC
	EONTAPI_ENOTFSCREENED
	EONTAPI_EISVDISK
	EONTAPI_EWAFLMSGABORTED
	EONTAPI_EMSGNULLIFY
	EONTAPI_ECOMPRESSCHECK
	EONTAPI_EVOLSMALL
	EONTAPI_EVOLBIG
	EONTAPI_EVOLPAIRED
	EONTAPI_EVOLNOTFLEX
	EONTAPI_EVOLSTALE
	EONTAPI_ENOREG
	EONTAPI_ENOREGKEY
	EONTAPI_ECANNOTDELETE
	EONTAPI_EWORMNOCLOCK
	EONTAPI_EWORMVOLWORM
	EONTAPI_EWORMVOLSLC
	EONTAPI_EWORMVOLNOTWORM
	EONTAPI_EWORMSNAPLOCKED
	EONTAPI_EWORMSNAPRENAME
	EONTAPI_EWORMPERIOD
	EONTAPI_ENOSPCAGGR
	EONTAPI_EVOLOPNOTSUPP
	ESWAPFILENOSPACE
	EONTAPI_EADMINOPQUIESCED
	EONTAPI_EWRONGSTRIPE
	EDATAUNRECOVERABLE
	ECLONEINPROGRESS
	EFILEIO
	EIPV6
	EMODE
	ENOPARTNERIFC
	EHOST_BADCONFIGURE
	EHOST_TRYAGAIN
	EHOST_MISC
	ECHECKRESULTS
	ELOOPBACK
	ENETMASKINVALID
	EIOCTLERROR
	EBROADCASTINVALID
	EVDISK_ERROR_NOT_IMPLEMENTED
	EVDISK_ERROR_NOT_QTREE_ROOT
	EVDISK_ERROR_NOT_VDISK_TYPE
	EVDISK_ERROR_NO_SUCH_INITGROUP
	EVDISK_ERROR_INITGROUP_EXISTS
	EVDISK_ERROR_NOT_VALID_FC_WWN
	EVDISK_ERROR_NOT_VALID_ISCSI_NAME
	EVDISK_ERROR_NODE_NOT_IN_INITGROUP
	EVDISK_ERROR_INITGROUP_HAS_NODE
	EVDISK_ERROR_LUN_MAPPING_CONFLICT
	EVDISK_ERROR_INITGROUP_WRONG_TYPE
	EVDISK_ERROR_NO_SUCH_ATTRIBUTE
	EVDISK_ERROR_VDISK_EXISTS
	EVDISK_ERROR_VDISK_EXPORTED
	EVDISK_ERROR_VDISK_NOT_ENABLED
	EVDISK_ERROR_VDISK_NOT_DISABLED
	EVDISK_ERROR_NO_SUCH_LUNMAP
	EVDISK_ERROR_NO_SUCH_VDISK
	EVDISK_ERROR_NOT_IN_SAME_QTREE
	EVDISK_ERROR_SOURCE_IS_VDISK
	EVDISK_ERROR_NO_SUCH_DIRECTORY
	EVDISK_ERROR_INVALID_SNAPSHOT_PATH
	EVDISK_ERROR_NOT_IN_SAME_VOLUME
	EVDISK_ERROR_INITGROUP_HAS_VDISK
	EVDISK_ERROR_INITGROUP_HAS_LUN
	EVDISK_ERROR_INITGROUP_MISSING_ARGS
	EVDISK_ERROR_INITGROUP_INVALID_ATTR_TYPE
	EVDISK_ERROR_INITGROUP_INVALID_ATTR_VALUE
	EVDISK_ERROR_NO_EXPORTED_VDISK_SHARE_WRITE
	EVDISK_ERROR_INITGROUP_MAPS_EXIST
	EVDISK_ERROR_VOLUME_NOT_SPACE_RESERVED
	EVDISK_ERROR_SNAPSHOT_FILE_NOT_VDISK
	EVDISK_ERROR_NITGROUP_INVALID_ATTR_VALUE_OS_TYPE
	EVDISK_ERROR_MUST_SPECIFY_F_FLAG
	EVDISK_ERROR_SIZE_TOO_LARGE
	EVDISK_ERROR_RESIZE_TOO_LARGE
	EVDISK_ERROR_NO_SUCH_VOLUME
	EVDISK_ERROR_USER_ABORT_ACTION
	EVDISK_ERROR_CLONING
	EVDISK_ERROR_INITIATOR_HAS_VDISK
	EVDISK_ERROR_FILE_IS_SPC_RESERVED
	EVDISK_ERROR_SIZE_TOO_SMALL
	EVDISK_ERROR_SIZE_UNCHANGED
	EVDISK_ERROR_NO_SUCH_SNAPSHOT
	EVDISK_ERROR_IGROUP_NOT_THROTTLED
	EVDISK_ERROR_IGROUP_ALREDY_THROTTLED
	EVDISK_ERROR_THROTTLE_TOO_MUHC
	EVDISK_ERROR_THROTTLE_BEING_DELETED
	EVDISK_ERROR_NO_SUCH_CLONE
	EVDISK_ERROR_NO_ISCSI_THROTTLES
	EVDISK_ERROR_INVALID_ATTR_MODE_VALUE
	EVDISK_ERROR_INITGROUP_MEMBER_CONFLICTING_OS_TYPES
	EVDISK_ERROR_INITGROUP_SET_TYPE_CONFLICT
	EVDISK_ERROR_INITGROUP_MEMBER_VSA_MIXED
	EVDISK_ERROR_INITGROUP_SET_VSA_CONFLICT
	EVDISK_ERROR_RESIZE_FIXES_NOT_GEOM_ALIGNED
	EVDISK_ERROR_RESIZE_VLD_TYPE_LUN_FIXES
	EVDISK_ERROR_RESIZE_IMGAG_TYPE_LUN_FIXES
	EVDISK_ERROR_INITGROUP_F_FLAG_REQUIRED
	EVDISK_ERROR_USE_PARTNER_NOT_APPLICABLE
	EVDISK_ERROR_RESTORE_WALKOVER_EACHOTHER
	EVDISK_ERROR_VOLUME_SPARSE
	EVDISK_ERROR_DESTROY_LUN_BUSY
	EVDISK_ERROR_CANT_CREATE_INITGROUP_FILE
	EVDISK_ERROR_CANT_WRITE_INITGROUP_FILE
	EVDISK_ERROR_CANT_RENAME_INITGROUP_FILE
	EVDISK_ERROR_CANT_CREATE_VFILER_SHADOW_INITGROUP_FILE
	EVDISK_ERROR_CANT_WRITE_VFILER_SHADOW_INITGROUP_FILE
	EVDISK_ERROR_CANT_RENAME_VFILER_SHADOW_INITGROUP_FILE
	EVDISK_ERROR_INITGROUP_TOO_MANY_NODENAMES
	EVDISK_ERROR_LUN_MISSING_FROM_SNAPSHOT
	EVDISK_ERROR_SNAPVALIDATOR_ERROR
	EVDISK_ERROR_PARTNER_HAS_LUN
	EVDISK_ERROR_PARTNER_NOT_REACHABLE
	EVDISK_ERROR_PORTSET_NO_SUCH_SET
	EVDISK_ERROR_PORTSET_ALREADY_EXIST
	EVDISK_ERROR_PORTSET_HAS_PORT
	EVDISK_ERROR_PORTSET_INVALID_PORT_NAME
	EVDISK_ERROR_PORTSET_TOO_MANY_PORTS
	EVDISK_ERROR_PORTSET_WRONG_TYPE
	EVDISK_ERROR_INITGROUP_ALREADY_BOUND
	EVDISK_ERROR_INITGROUP_NOT_BOUND
	EVDISK_ERROR_INITGROUP_EMPTY_PSET_BIND
	EVDISK_ERROR_PORTSET_NO_SUCH_PORT
	EVDISK_ERROR_PORTSET_NO_SUCH_FILER_NAME
	EVDISK_ERROR_PARTNER_HAS_DIFFERENT_OS_TYPE
	EVDISK_ERROR_PARTNER_HAS_DIFFERENT_VSA_SETTING
	EVDISK_ERROR_PORTSET_CANT_CREATE_FILE
	EVDISK_ERROR_PORTSET_CANT_WRITE_FILE
	EVDISK_ERROR_PORTSET_CANT_READ_FILE
	EVDISK_ERROR_PORTSET_CANT_OPEN_FILE
	EVDISK_ERROR_LUN_TOO_LARGE
	EVDISK_ERROR_PORTSET_IC_DOWN
	EVDISK_ERROR_CLONE_NOT_SPLITTING
	EVDISK_ERROR_LUN_HAS_NO_SERIAL_NO
	EVDISK_ERROR_PORTSET_THROTTLE_EXCEEDED
	EVDISK_ERROR_PORTSET_CANT_DESTROY_BOUND_PORTSET
	EVDISK_ERROR_CFMODE_MISMATCH
	EVDISK_ERROR_PORTSET_NOT_VALID_CFMODE
	EVDISK_ERROR_CANNOT_CHANGE_SPCRES_DURING_SPLIT
	EVDISK_ERROR_INITGROUP_BIND_WRONG_TYPE
	EVDISK_ERROR_DB_BAD_INDEX
	EVDISK_ERROR_DB_NO_SUCH_DATABASE
	EVDISK_ERROR_ALUA_NOT_SUPPORTED_ON_ISCSI
	EVDISK_ERROR_ALUA_NOT_SUPPORTED_ON_CFMODE
	EVDISK_ERROR_PORTSET_INVALID_PARTNER_PORT_NAME
	EVDISK_ERROR_PORTSET_BOTH_INVALID_PORT_NAMES
	EVDISK_ERROR_PARTNER_WWNN_MISMATCH_FOR_SSI
	EVDISK_ERROR_INVALID_DEVICE_ID
	EVDISK_ERROR_WWPN_ALIAS_NOT_FOUND
	EVDISK_ERROR_WWPN_ALIASES_NOT_SET
	EVDISK_ERROR_WWPN_ALIASES_TOO_MANY
	EVDISK_ERROR_WWPN_ALIAS_INVALID
	EVDISK_ERROR_QTREE_PRESERVE_FAILED
	EVDISK_ERROR_QTREE_RESTORE_FAILED
	EVDISK_ERROR_QTREE_CLEANUP_FAILED
	EVDISK_ERROR_PREFIX_SUFFIX_SIZE_MISMATCH
	EVDISK_ERROR_ALUA_ISCSI_TRANSPORT_TYPE_CONFLICT
	EVDISK_ERROR_ALUA_FCP_TRANSPORT_TYPE_CONFLICT
	EVDISK_ERROR_LUN_HAS_ALUA_ENABLED_ISCSI_IGROUP
	EVDISK_ERROR_LUN_HAS_ALUA_ENABLED_FCP_IGROUP
	EVDISK_ERROR_LUN_HAS_ISCSI_IGROUP
	EVDISK_ERROR_LUN_HAS_FCP_IGROUP
	EVDISK_ERROR_LUN_HAS_ALUA_CONFLICTS
	EVDISK_ERROR_PORTSET_TOO_FEW_PORTS
	EVDISK_ERROR_WWPN_NOT_FOUND
	EVDISK_ERROR_WWPN_ALIAS_REMOVE_INVALID_NUM_ARGS
	EVDISK_ERROR_IN_TAKEOVER
	EVDISK_ERROR_WWPN_ALIAS_ALREADY_SET
	EVDISK_ERROR_VOLUMES_ONLINING
	EVDISK_ERROR_VIRTUAL_LUN_MAPPING_CONFLICT
	EVDISK_ERROR_LUN_STREAM_DATAUNRECOVERABLE
	EVDISK_ERROR_VDISK_NOT_STOPPED
	EVDISK_ERROR_INVALID_PREFIX_SIZE
	EVDISK_ERROR_INVALID_SUFFIX_SIZE
	EAPIERROR
	EAPIAUTHENTICATION
	EAPIPRIVILEDGE
	EAPIPRIVILEGE
	EAPIEXCEPTION
	EAPINOTFOUND
	EAPIMISSINGARGUMENT
	EAPINOTIMPLEMENTED
	EAPILICENSE
	EAPIINDEXTOOLARGE
	EAPIUNSUPPORTEDVERSION
	EAPITRANSMISSION
	EOPNOTSUPPORTED
	EALREADYSTARTED
	ENOTSTARTED
	ESERVICENOTSTOPPED
	ENOTWHILEWAITINGFORGIVEBACK
	ENOTINMAINTMODE
	ENOTINREADONLYMODE
	EAPITOOMANYENTRIES
	ESNAPSHOTEXISTS
	ESNAPSHOTDOESNOTEXIST
	ESNAPSHOTTOOMANY
	ESNAPSHOTNOTALLOWED
	ESNAPSHOTBUSY
	ESNAPSHOTNOSPACE
	EDUPLICATEDSID
	EINVALIDDSID
	EINVALIDMSID
	EAMBIGUOUS_DSID
	ESNAPSHOT_NOT_LATEST
	ESTRIPEDRESTOREOPNOTFOUND
	EVOLUMESNAPRESTOREERROR
	EVOLUMEQUIESCED
	EVOLUMEDOESNOTEXIST
	EVOLUMEMOUNTING
	EVOLUMEOFFLINE
	EVOLUMEREADONLY
	EVOLUMENAMEINVALID
	EVOLUMERGSIZEINVALID
	EVOLUMELANGUAGEINVALID
	EVOLUMEDISKSIZEINVALID
	EVOLUMEDISKDUP
	EVOLUMERGINVALID
	EQUOTAPARSEERROR
	EQUOTAINVALID
	EQUOTAEXISTS
	EQUOTADOESNOTEXIST
	EQUOTADIRECTIVE
	EAPI_CONNECTION
	EAPI_CONNECTION_DROPPED
	EAPI_RECEPTION
	EVOL_NOT_OFFLINE
	EVOL_NOT_RESTRICTED
	EVOL_ONLINE
	EVOL_RESTRICTED
	EVOL_SPACE_FOR_GUARANTEE
	EVOL_TOO_MANY
	EVOLUME_NOT_QUIESCED
	EVOLUME_CLEAR_QUIESCE
	EVOLUME_ALREADY_QUIESCED_SET
	EVOLUME_ALREADY_QUIESCED_CLEAR
	EVOL_CIFS_OPENS
	EVOL_INVALID_FSINFO
	EVFILEROPNOTALLOWED
	EVFILERNOTFOUND
	EVFILEROPNOTCOMPLETED
	EIPSPACENOTFOUND
	EVOL_UNKNOWN_VERSION
	EVOL_CIFS_ENABLED
	EQTREEEXISTS
	EQTREENOTOWNER
	EQTREEMAX
	ECMSINVALIDREQUEST
	ECMSNOTENABLED
	ECMSPROCESSINGERROR
	ESNAPMIRROROFF
	ESNAPMIRRORPARSERERROR
	ESNAPMIRRORERROR
	EISCSISECINVALIDAUTHTYPE
	EISCSISECINVALIDINPUTERROR
	EISCSISECPROCESSINGERROR
	EISCSISECINITNOTFOUNDERROR
	EFILENOTFOUND
	EINTERNALERROR
	EINVALIDINPUTERROR
	ESETSPCRESERROR
	EADAPTERNOTFOUND
	EADAPTERPARTNER
	EADAPTERINVALIDTYPE
	ENOADAPTERPARTNER
	ENOVIRTUALADAPTERS
	ENOTCLUSTERED
	ECLUSTERED
	EDISKNOTFOUND
	ESWAPINPROGRESS
	ENOTDISKOWNER
	EDISKINRAIDZEROVOL
	EDISKISSPARE
	EVOLUMEPLEXINVALID
	EVOLUMEINUSE
	EVOLUMENOTONLINE
	EVOLUMEBUSY
	EVOLUMECIFSTERMINATE
	EVOLUMECREATING
	ECLIENTSTATSVFILER
	ECLIENTSTATSNOTENABLED
	ENOACTIVECLIENTS
	ECIFSNOTCONFIGURED
	EDNSNOTENABLED
	EHOSTNOTFOUND
	ELDAPSVRNOTFOUND
	EVOL_ONLINE_ERROR
	EVOL_PARTIAL
	EVOLNOTCLONE
	EVOLOPNOTUNDERWAY
	EVOLUME_NOT_QUIESCED_MISSING_PARAMS
	EVOLUME_NOT_QUIESCED_NOMORE_SNAPSHOTS
	EVOLUME_NOT_QUIESCED_SNAP_CREATE_BUSY
	EVOLUME_NOT_QUIESCED_TIMEDOUT
	EVOLUME_NOT_QUIESCED_PENDING_VOL_REFS
	EVOLUME_NOT_QUIESECED_PENDING_SNAP_REFS
	EVOLUME_NOT_QUIESCED_PENDING_MSGS
	EVOLUME_NOT_QUIESCED_CP_SYNC_TIMEDOUT
	EVOLUME_NOT_QUIESCED_SNAPSHOT_EXISTS
	EVOLUME_NOT_QUIESCED_SNAP_SCHED_ABORT_TIMEDOUT
	EVOLUME_NOT_QUIESCED_ZOMBIE_DRAIN_TIMEDOUT
	EVOLUME_NOT_QUIESCED_SNAP_CREATE_TIMEDOUT
	EVOLUME_NOT_QUIESCED_CLONE_FROM_SNAPSHOT_EXISTS
	EVOLUME_NOT_QUIESCED_CANT_CREATE_SNAPSHOT
	EVOLUME_NOT_QUIESCED_CANT_CREATE_SNAPSHOT_NO_SPACE
	ESVCDISABLED
	ESVCNOTAVAIL
	ESHAREACCESSDENIED
	ESHAREEXISTS
	ESHARETOOMANY
	ECIFSSHARINGVIOLATION
	ESANOWNNOTENABLED
	EINVALIDHOST
	EINVALIDOWNERID
	EINVALIDOWNER
	EINVALIDPASSWORD
	EEXPORTSINCOMPATIBLE
	EINODENUMBERTOOSMALL
	EINODENUMBERTOOLARGE
	EINVALIDINODE
	EINELIGIBLEINODE
	EPARENTINFONOTLOADED
	EI2PNOTENABLED
	EVV_COMMON
	ECIFS_LOGIN_FAILED
	ECIFS_BIND_FAILED
	ECIFS_DNS_REQUIRED
	ECIFS_KRB_CONFLICT
	ECIFS_AD_CLOCK_SKEW
	ECIFS_AD_RESET_REQUIRED
	ECIFS_LIST_UNAVAILABLE
	ECIFS_DC_CONNECT_FAILED
	ECIFS_HAVE_SESSION_SCOPED_LOCKS
	ECIFS_PASSWD_AND_GROUP_REQUIRED
	ECIFS_SETUP_CANNOT_WRITE
	EEMS_INVOKE_FAILED
	EEMS_INVOKE_BAD_PARAM
	EEMS_INVOKE_ID_BAD
	EEMS_INVOKE_SEVERITY_REQUIRED
	EEMS_INVOKE_SEVERITY_INVALID
	EEMS_INVOKE_SEVERITY_NOT_VARIABLE
	EEMS_INVOKE_PARAMS_INSUFFICIENT
	EEMS_INVOKE_VERSION_INVALID
	EEMS_INVOKE_SUPRESS_DUP
	EEMS_INVOKE_SUPRESS_TIMER
	EEMS_INVOKE_NVRAM_TOO_BIG
	EEMS_INVOKE_QUEUE_FULL
	EREALLOCATE_EXISTS
	EREALLOCATE_BADPATH
	EREALLOCATE_NOMEM
	EREALLOCATE_NOSCAN
	EREALLOCATE_BADVOL
	EREALLOCATE_READONLY
	EREALLOCATE_BADSCHED
	EREALLOCATE_OFF
	EREALLOCATE_SNAPSHOT
	EDISKNOTSPARE
	EDISKTOOSMALL
	ERAIDGROUPDEGRADED
	ESAVECOREDISK
	EINVALIDSTATE
	ECANT_USE_ALL_DISKS
	ENPMINVPLOC
	ENPMNOPKG
	ENPMNOMETA
	ENPMERXMETA
	EINCRCOPYFAILED
	EINCRCOPYOPNOTFOUND
	EINCRCOPYINVALIDUUID
	EINCRCOPYINVALIDOP
	EINCRCOPYNOMEM
	EINCRCOPYINVALIDINPUT
	EINCRCOPYINVALIDOPTYPE
	EINCRCOPYDUPLICATESESSION
	EINCRCOPYNOTSUPPORT
	EINCRCOPYVOLOFFLINE
	EINCRCOPYVOLNOTFOUND
	EINCRCOPYSNAPCREATIONFAIL
	EINCRCOPYSNAPSHOTEXIST
	EINCRCOPYNOSTREAMESTABLISHED
	EINCRCOPYAGAIN
	EINCRCOPY_CSM_CALL_FAIL
	EINCRCOPY_CSM_SEND_FAIL
	EINCRCOPY_CSM_CANT_GET_SESSION
	EINCRCOPY_CSM_CANT_REGISTER_SENDCB
	EDSIDPARSEERROR
	EINCRCOPY_SET_INCORE_QUIESCE_VOL_FAIL
	EINCRCOPY_UNSET_INCORE_QUIESCE_VOL_FAIL
	EINCRCOPY_SET_ONDISK_QUIESCE_VOL_FAIL
	EVOLMOVE_NDMP_DUMPS_RUNNING
	EINCRCOPY_DUMPS_RUNNING
	EVOLMOVE_NDMP_RESTORE_RUNNING
	EINCRCOPY_RESTORE_RUNNING
	EVOLMOVE_SIS_UNDO_RUNNING
	EVOLMOVE_WAFL_ERR
	EVOLMOVE_AGENT_IS_INITIALIZING
	EVOLMOVE_LOCKED_FOR_SNAPMIRROR
	ECGERROR
	ECGSNAPERR
	ECGOFF
	ECHARMAP_INVALID
	ECHARMAP_NO_PERSIST
	ETOERRMIN
	ESERVICENOTINITIALIZED
	ESERVICENOTLICENSED
	ESERVICENOTENABLED
	EMBOXDEGRADED
	EMBOXUNKNOWN
	EMBOXVERSIONMISMATCH
	EPARTNERDISABLEDTO
	EOPERATORDENY
	ENVRAMSIZEMISMATCH
	EVERSIONMISMATCH
	EINTERCONNECTERROR
	EPARTNERBOOTING
	ESHELFHOT
	EPARTNERREVERT
	ELOCALREVERT
	EPARTNERTRYINGTAKEOVER
	ETAKEOVERINPROGRESS
	EHALTNOTAKEOVER
	EUNSYNCNVRAM
	EUNKNOWNTAKEOVERERROR
	EWAITINGFORPARTNER
	ELOWMEMORY
	EHALTING
	EMBOXUNCERTAIN
	ENOAUTOTAKEOVER
	EPARTNERNOTWAITING
	ENOAGGRS
	EOP_DISALLOWED_DURING_GIVEBACK
	EOP_DISALLOWED_BRINGING_OFFLINE
	EOP_DISALLOWED_BRINGING_ONLINE
	EOP_DISALLOWED_DURING_DESTROY
	EOP_DISALLOWED_VOLUME_FENCED
	EOP_DISALLOWED_VOLUME_FROZEN
	EOP_DISALLOWED_VOLUME_OLDLABELS
	EOP_DISALLOWED_VOLUME_NEEDED_LAZY_SPCRSRV
	ENOPARTNERINVENTORY
	EPARTNERMISSINGDISKS
	ENOTHINGTOTAKEOVER
	ESENDHOMEINPROGRESS
	ENVRAMDOWN
	EINTERCONNECTRESET
	EBADOPTIONS
	ENOTHALTED
	EREVERTINPROGRESS
	ESERVICEENABLED
	EINTAKEOVER
	ETOERRMAX
	EOPLOCKRECALLFAILED
	EOP_DISALLOWED_DURING_REVERT
	EVOLUME_ADMINOP_NOT_FENCED
	EINVALIDRESERVATION
	ENODISKSFOUND
	EMUSTBEINMAINTMODE
	EFILEEXISTS
	EJUNCTIONEXISTS
	EJUNCTIONDOESNOTEXIST
	EBADFILELENGTH
	EFILER_NOT_HEALTHY
	EBADCOREID
	ECOREDUMPBUSY
	ECOREDUMPNOTINITIALIZED
	ESESNOTREADY
	ESESBUSY
	ERDB_HA_SF_NOT_INITIALIZED
	ERDB_HA_ID_MISMATCH
	ERDB_HA_CONFIGURED
	ERDB_HA_PARTIALLY_CONFIGURED
	ERDB_HA_NOT_CONFIGURED
	ERDB_HA_CONFIG_UUID_MISMATCH
	ERDB_HA_CANNOT_EXIT_CONFIG
	ERDB_HA_IO_ERROR
	ERDB_HA_INVALID_SLOT
	ERDB_HA_OLD_COOKIE
	ERDB_HA_INVALID_INPUT
	ERDB_HA_FAILURE
	ERDB_HA_ILLEGAL_SLOT_CONTENT
	ERDB_HA_SLOT_UUID_MISMATCH
	ERDB_HA_QUIESCENT_PERIOD
	EFIJIINVALID
	EFIJIINVALIDEXPR
	EFIJINOFILTER
	EFIJIMAXFILTERS
	EAGGRDOESNOTEXIST
	EAGGRNOTONLINE
	EAGGRFAILINGOVER
	EAGGRMISMATCH
	ENFS_CLIENT_STATS_NOT_ENABLED
	ELOOPUNAVAILABLE
	ESNAPSHOTEXISTSPARTIAL
	ESNAPVAULTERR
	ESNAPVAULTSETUP
	ESNAPVAULTRESOURCE
	ESNAPVAULTBUSY
	EVOLUME_NOT_QUIESCED_NOT_MOUNTED
	EVOLUME_NOT_QUIESCED_ROOT_VOLUME
	EVOLUME_NOT_QUIESCED_NOT_FLEX
	EVOLUME_NOT_QUIESCED_IRONING
	EVOLUME_NOT_QUIESCED_GOING_HOME
	EVOLUME_NOT_QUIESCED_CB_TIMEOUT
	EVOLUME_NOT_QUIESCED_NOT_DRAIN
	EVOLUME_NOT_QUIESCED_FOR_CORAL
	EVOLAGGRISIRONING
	EVOLUME_HAS_VFILER_STORAGE
	EVOLUME_QUIESCING
	EVOLUME_NOT_BOOLEAN_VALUE
	EVOLUME_TYPE_NOT_SUPPORTED
	EVOLISGRIDIRONING
	EONTAPI_ESNAPDIFF_FILENAME_UNAVAILABLE
	EVOLUME_NOT_QUIESCED_SAN_NOTIFICATION_TIMEOUT
	EONTAPI_ESNAPDIFF_FILETYPE_MODIFIED
	ELOGROTATIONACTIVE
	ESNAPDIFFINTERROR
	ESNAPDIFFINVINPUT
	ESNAPDIFFINVSNAPSHOT
	ESNAPDIFFSNAPSHOTCHANGED
	ESNAPDIFFSNAPSHOTEARLIER
	ESNAPDIFFMAXSESSIONSEXCEEDED
	ESNAPDIFFDUPLICATESESSION
	ESNAPDIFFINVALIDSESSION
	ESNAPDIFFNOI2P
	ESNAPDIFFVOLOFFLINE
	ESNAPDIFFABORTED
	EVOLUMEGSMINVALID
	EAPIMISSINGOUTPUT
	EINVALIDOUTPUTERROR
	EVOLUMECOMPRESSED
	EVOLUMENOTDECOMPRESSING
	ENOTIMEZONESET
	ENOTIMEZONEVERSION
	EINVALIDTIMEZONE
	ETIMEZONEDIFFERENTINRC
	ESNAPLOCKNOTLICENSED
	ECOMPLIANCECLOCKNOTSET
	ETAKENOVER
	EDATENOTSETONPARTNER
	ERSHSESSIONERROR
	ERSHKILLERROR
	EDENSE_REVERTING
	EDENSE_IRON_RUNNING
	EDENSE_CLONE_SFSR_INPROG
	EDENSE_NLCSR_INPROG
	EDENSE_VOL_NONEXIST
	EDENSE_VOL_OFFLINE
	EDENSE_VOL_NOTSUP
	EDENSE_VOL_RDONLY
	EDENSE_VOL_TRANSITING
	EDENSE_VOL_RESTRICTED
	EDENSE_SNAPSHOT_CREATE
	EDENSE_SNAPSHOT_DELETE
	EDENSE_SNAPSHOT_NONEXIST
	EDENSE_STALE_DINODE
	EDENSE_STALE_RINODE
	EDENSE_STALE_DBUF
	EDENSE_STALE_RBUF
	EDENSE_CIFS_HOLE_RERVD
	EDENSE_DONOR_TOO_SMALL
	EDENSE_RECIPIENT_TOO_SMALL
	EDENSE_NO_SPACE
	EDENSE_SHUTDOWN
	EDENSE_FAILOVER
	EDENSE_DONOR_RANGE
	EDENSE_RECPT_RANGE
	EDENSE_QUOTA_CHECK
	EDENSE_UNSUPPORTED_VOLTYPE
	EDENSE_CLONE_SPLITTING
	EDENSE_CLONE_STOPPED
	EDENSE_CLONE_SFILE_NONEXIST
	EDENSE_CLONE_CFILE_NONEXIST
	EDENSE_CLONE_NO_SLOT
	EDENSE_CLONE_NO_ARGS
	EDENSE_CLONE_DIFF_VOLUME
	EDENSE_CLONE_SAME_FILE
	EDENSE_CLONE_VOL_REVERTING
	EDENSE_CLONE_IN_PROG
	EDENSE_CLONE_SNAPNAME
	EDENSE_CLONE_SNAPPATH
	EDENSE_CLONE_SNAP_FH
	EDENSE_CLONE_SNAP_ATTR
	EDENSE_CLONE_SFILE_ATTR
	EDENSE_CLONE_CFILE_ATTR
	EDENSE_CLONE_EXIST
	EDENSE_CLONE_METAFILE
	EDENSE_CLONE_METAFILE_FH
	EDENSE_CLONE_METAFILE_WRITE
	EDENSE_CLONE_METAFILE_ATTR
	EDENSE_CLONE_METAFILE_READ
	EDENSE_CLONE_SFILE_READ
	EDENSE_CLONE_CFILE_WRITE
	EDENSE_CLONE_FH
	EDENSE_CLONE_CREATE
	EDENSE_CLONE_SETATTR
	EDENSE_CLONE_SOURCE_FH
	EDENSE_CLONE_NOT_SUPP
	EDENSE_CLONE_PROC
	EDENSE_CLONE_TYPE_SUPP
	EDENSE_CLONE_SRC_OUTOF_RANGE
	EDENSE_CLONE_DEST_OUTOF_RANGE
	EDENSE_CLONE_OVERLAP_RANGE
	EDENSE_CLONE_INVALID_RANGE
	EDENSE_CLONE_RUNNING_OP
	EDENSE_CLONE_NOT_RUNNING
	EDENSE_CLONE_NO_OP
	EDENSE_CLONE_NOT_FAILED
	EDENSE_CLONE_DEL_INFO
	EDENSE_CLONE_PENDING_SNAP
	EDENSE_CLONE_SPLIT_MAP
	EDENSE_CLONE_INVALID_SOURCE
	EDENSE_CLONE_INVALID_CLONE
	EDENSE_CLONE_SNAP_DEL
	EDENSE_CLONE_GET_SNAPID
	EDENSE_CLONE_SMALL_DATA
	EDENSE_VDISK_INVALID_NAME
	EDENSE_VDISK_NOT_IN_QTREE_ROOT
	EDENSE_VDISK_VOL_SPARSE_WO_SCSI
	EDENSE_VDISK_INTERNAL_ERROR
	EDENSE_VDISK_INVALID_FH
	EDENSE_VDISK_NO_SUCH_VDISK
	EDENSE_VDISK_LBA_OFFSET_MISALIGNED
	EDENSE_VDISK_SRC_INVALID_BLOCK_RANGE
	EDENSE_VDISK_DST_INVALID_BLOCK_RANGE
	EDENSE_VDISK_SRC_LUN_CLONE
	EDENSE_CLONE_MAX_OPS_VOL
	EDENSE_CLONE_INVALID_DIR
	EDENSE_CLONE_NOT_QTREE_ROOT
	EDENSE_CLONE_LARGE_INFO
	EDENSE_CLONE_INVALID_ID
	EDENSE_CLONE_NOT_LICENSED
	EDENSE_CLONE_LICENSE_EXPIRED
	EDENSE_CLONE_FILE_FOLD_INPROG
	EDENSE_CLONE_WORM_VOL
	EDENSE_CLONE_INVALID_UUID
	EDENSE_CLONE_EXISTING_OP
	EDENSE_CLONE_CHANGELOG_OFF
	EDENSE_NON_SUPPORTED_PLATFORM
	EDENSE_STALE_CLONE_DIR_INODE
	EDENSE_CLONE_DIR_FH
	EDENSE_CLONE_MAX_OPS_FILER
	EDENSE_CLONE_METAFILE_VER_MISMATCH
	EDENSE_UNKNOWN
	EROUTEEXISTS
	EINVALIDROUTE
	EROUTENOTFOUND
	EVLANEXISTS
	EINTERFACENOTFOUND
	EIPSPACEEXISTS
	EIPSPACEDOESNOTEXIST
	EDENSE_CLONE_MAX_OPS_VFILER
	EDENSE_CLONE_SRC_VFACCESS
	EDENSE_CLONE_DST_VFACCESS
	EDENSE_CLONE_VFILER_NOT_RUNNING
	EDENSE_VFILER_CUTOVER
	EDISKTYPEWRONGFORSNAPLOCK
	EDISKTYPEWRONGFORVOL
	EDISK_TYPE_MISMATCH
	EVOL_ALREADY_MOUNTED
	EVOL_MOUNT_FAILED
	EJUNCTION_CREATE_FAILED
	EVOL_NOT_MOUNTED
	EVOL_UNMOUNT_FAILED
	EJUNCTION_DELETE_FAILED
	EVSERVER_OP_NOT_ALLOWED
	EDENSE_COMP_SCAN_ACTIVE
	EDENSE_CLONE_SUB_COMPRESSION
	EDENSE_CLONE_DECOMP_ACTIVE
	EINVALIDPATH
	EVSERVERNAMEEXISTS
	EVSERVERALREADYSTARTED
	EVSERVERNOTRUNNING
	ESIS_CLONE_VOL_NONEXIST
	ESIS_CLONE_VOL_OFFLINE
	ESIS_CLONE_VOL_NOTSUP
	ESIS_CLONE_VOL_RDONLY
	ESIS_CLONE_VOL_TRANSITING
	ESIS_CLONE_STALE_INODE
	ESIS_CLONE_STALE_DINODE
	ESIS_CLONE_STALE_RINODE
	ESIS_CLONE_SHUTDOWN
	ESIS_CLONE_FAILOVER
	ESIS_CLONE_CLONE_SFILE_NONEXIST
	EVOL_NFS_ENABLED
	ESIS_CLONE_CLONE_DIFF_VOLUME
	ESIS_CLONE_CLONE_SFILE_ATTR
	ESIS_CLONE_CLONE_CFILE_ATTR
	ESIS_CLONE_CLONE_FH
	ESIS_CLONE_CLONE_SOURCE_FH
	ESIS_CLONE_CLONE_TYPE_SUPP
	ESIS_CLONE_NLCSR_INPROG
	ESIS_CLONE_CLONE_OVERLAP_RANGE
	ESIS_CLONE_CLONE_INVALID_RANGE
	ESIS_CLONE_CLONE_INVALID_SOURCE
	ESIS_CLONE_CLONE_INVALID_CLONE
	ESIS_CLONE_CLONE_INVALID_DIR
	ESIS_CLONE_CLONE_WORM_VOL
	ESIS_CLONE_VDISK_INVALID_NAME
	ESIS_CLONE_CLONE_EXIST
	ESIS_CLONE_SFILE_READ
	ESIS_CLONE_CFILE_WRITE
	ESIS_CLONE_LICENSE_EXPIRED
	ESIS_CLONE_NOT_LICENSED
	EVOL_IN_NVFAILED_STATE
	EQUOTAS_NO_VALID_RULES
	EQUOTA_POLICY_NOT_FOUND
	ESIS_CLONE_DECOMP_ACTIVE
	ESIS_CLONE_SPLIT_MAP
	ESIS_CLONE_SOURCE_TOO_SMALL
	ESIS_CLONE_DOWNGRADE
	ESIS_CLONE_FLEXCLONE_SPLITTING
	ESIS_CLONE_CLONE_INVALID_SPC_RSRV
	ESIS_CLONE_UNKNOWN
	ESIS_CLONE_MAX_RANGES
	ESIS_CLONE_MAX_BLKS
	ESIS_CLONE_CLONE_CFILE_NONEXIST
	ESNAPMIRROR_NOT_INITIALIZED
	EAGGR_TOO_LARGE
	EQTREE_SECURITY_GET_FAILED
	EQTREE_OPLOCK_GET_FAILED
	EINTENTLOG_READ_FAILED
	EOPLOCKS_TOO_MANY_RECALLS_PENDING
	ESNAPMIRRORSUBSYSTEMNOTINITED
	EQUOTA_CONTROL_METAFILE_OPEN
	EQUOTA_CONTROL_METAFILE_READ
	EMAXFILES_TOO_LARGE
	ESNAPMIRRORDESTSTATEINVALID
	EILLEGAL_INODE_CHECK
	ECOL_COPY_INVALIDINPUTERROR
	ECOL_COPY_INTERNALERROR
	ECOL_COPY_FILENOTFOUND
	ECOL_COPY_NORESOURCES
	ECOL_COPY_NOACCESSTOSRC
	ECOL_COPY_VOLOFFLINE
	ECOL_COPY_DSTREADONLY
	ECOL_COPY_ISDIRECTORY
	ECOL_COPY_NOSPACE
	ECOL_COPY_COPYFAILED
	ECOL_STATUS_INVALIDINPUTERROR
	ECOL_STATUS_COPYIDNOTFOUND
	ECOL_STATUS_INTERNALERROR
	ECOL_ABORT_INVALIDINPUTERROR
	ECOL_ABORT_INTERNALERROR
	ECOL_ABORT_COPYIDNOTFOUND
	ETELNETSHUTDOWNERROR
	ECORALSET_ONLINE_FAILED
	ESTRIPEDVOL_NOT_FULLY_ONLINE
	EVOL_BAD_VVLABEL_CKSUM
	EVOL_BAD_VVLABEL_MAGIC
	EVOL_BAD_VVLABEL_UUID
	EVOL_BAD_VVLABEL_VERSION
	EVOL_FAILED_TO_ONLINE
	EVOL_INCOMPLETE
	EVOL_MIRROR_TYPE_INVALID
	EVOL_BAD_MODE_BITS
	ECOMPRESSING
	EVOLUMENOTCOMPRESSENABLED
	ECOMPRESSIONGATHERER
	ECOMPSHARINGBEYONDLIMIT
	ECOMPRESSCLONEINPROG
	EIRON_STREAM_DIR_UPGRADE
	EIRON_UPGRADE_DISALLOWED
	EIRON_NOT_RUNNING
	EIRON_OC_DISALLOWED
	EIRON_PREV_CP_DISALLOWED
	EIRON_QTREE_READONLY
	EIRON_ROOT_AGGR_DISALLOWED
	EIRON_SCANS_DISALLOWED
	EIRON_SPARSE_VOL_NOT_ONLINE
	EIRON_STARTING
	EIRON_STOP_IN_PROGRESS
	ESNAPMIRRORTRANSFERFAILED
	ESNAPMIRRORINVALIDUUID
	ESNAPMIRRORINVALIDINPUT
	ESNAPMIRRORNOMEM
	ESNAPMIRRORNOTSUPPORT
	ESNAPMIRRORVOLNOTFOUND
	ESNAPMIRROROPNOTFOUND
	EQTREE_DOES_NOT_EXIST
	EQTREE_HAS_SHARES
	EQTREE_HAS_FILES
	EQUOTAS_ON
	EQUOTAS_OFF
	EOP_DISALLOWED_ON_NOT_HOME_AGGR
	EOP_DISALLOWED_ON_ROOT_AGGR
	EOP_DISALLOWED_ON_AGGR_WITH_NODE_VOLS
	EOP_DISALLOWED_ON_STRIPED_AGGR
	EINVALID_HA_POLICY
	ESTAMPREDIRECTSNAPIDERROR
	EQUOTAS_OPERATION_MISMATCH
	EVOLUME_OP_NOT_SUPPORTED_BY_OWNER
	EOP_ERR_MODE_MISMATCH_OBJ_ORIGINALLY_CLUSTERED
	EOP_ERR_MODE_MISMATCH_OBJ_ORIGINALLY_UNCLUSTERED
	EOP_CLUSTER_ATTR_DISALLOWED
	ESNAPMIRRORTRANSFEREXISTS
	ESNAPMIRRORCHECKMISMATCH
	ESNAPMIRRORIMAGENOTFOUND
	ESNAPMIRRORSTREAMNOTFOUND
	ESNAPMIRRORTRANSFERNOTFOUND
	ESNAPMIRRORSESSIONNOTFOUND
	ESNAPMIRRORTRANSFERNOTCOMPLETE
	ESNAPMIRRORINTERNALERROR
	ESNAPMIRROROTHER
	EARRAYNOTFOUND
	EOP_DISALLOWED_ON_CFO_AGGR
	EOP_DISALLOWED_ON_SFO_AGGR
	ENODENOTFOUND
	EVSERVERNOTFOUND
	EUSECLUSTERNATIVEUI
	ESCHEDNOTFOUND
	EMULTIPLEVOLSFOUND
	EVERSION_INVALIDRANGE
	EVERSION_EXISTS
	ERESOURCEINUSE
	EVOL_MANIFEST_NOT_AVAILABLE
	EVOL_MANIFEST_QUERY_NOT_DEFINITIVE
	EVOL_TRANS_BLOCKING_FEATURES
	EUNABLE_TO_UPDATE_VOLDB
	EVOL_UNABLE_TO_SET_UP_SNAPSHOT_XLATE_TABLE
	EAGGR_SNAPSHOT_IN_PROGRESS
	EAGGR_HAS_SNAPSHOTS
	EAGGR_HAS_UNSUPPORTED_VOLUME
	EAGGR_CANT_UNDO_HYBRID
	EAGGR_HYBRID
	EOP_DISALLOWED_ON_SSD_AGGR
	ENOT_A_AZCS_DISK
	ENO_AZCS_DISKS
	EMCS_NOT_ALLOWED_WITH_LUNS
	EAGGR_ZONED_NOT_ALLOWED_WITH_DISKS
	ESNAPSHOTRESTOREINPROGRESS
	ESNAPSHOTTAGSERR
	ESNAPSHOTINVALIDID
	ESNAPSHOTTAGSNOSPACE
	ESNAPSHOTTAGSMETAFILEERR
	EVOL_NOT_IRON_RESTRICTED
	EIRON_NOT_OPTCOMMIT
	EVOL_HAS_REPLICA
	EDENSE_VOL_COMPRESSED
	EDENSE_CG_MISMATCH
	EMULTIPLEOPTSFOUND
	EVOLUME_64BIT_UPGRADE_MODE_INVALID
	EAGGR_WOULD_UPGRADE
	EAGGR_64BIT_UPGRADE_NOT_IN_PROGRESS
	EAGGR_SIZE_LESS_THAN_16TB
	EAGGR_64BIT_UPGRADE_ENOSPC
	EVOLUME_64BIT_UPGRADE_VVOL_ENOSPC
	EAGGR_64BIT_UPGRADE_RESTRICTED
	EOP_DISALLOWED_ON_TRAD
	EVOLUME_ALREADY_64BIT
	EVOLUME_64BIT_UPGRADE_DISALLOWED
	EVOLUME_CANT_OBTAIN_VOLREF
	EVOLUME_64BIT_UPGRADE_KIREETI_NOT_AVAIL
	EVOLUME_64BIT_UPGRADE_PREQUAL_NOT_AVAIL
	EVOLUME_64BIT_UPGRADE_ESTIMATE_IN_PROGRESS
	EONTAPI_VOLTRANS_JOBNOTFOUND
	EONTAPI_VOLTRANS_LOG_INVALIDOFFSET
	EONTAPI_VOLTRANS_LOG_REC_NOTFOUND
	EDENSE_DEDUPE_NOT_DISABLED
	EDENSE_COMPRESSION_NOT_DISABLED
	EDENSE_CONCURRENT_LIMIT
	EAGGR_MIGRATE_CORE
	ESHUTDOWN_INPROGRESS
	ENOT_HOMED_TO_PARTNER
	ENOT_SFO_HA_POLICY
	EAGGR_FAILED_LIMBO
	EAGGR_MIGRATE_OFFLINE_FAILED
	EAGGR_MIGRATING
	EAGGR_MIGRATE_VETO
	EDENSE_VOL_NOT_TRANSITIONED
	ESNAPMIRRORVOLUMENOTQUIESCED
	ESNAPMIRRORTRANSFERCOMPLETE
	ESNAPMIRRORCHECKSUMERROR
	ESNAPMIRRORNETWORKERROR
	ESNAPMIRRORVOLUMEIDERROR
	ESNAPMIRRORFILESYSTEMERROR
	ESNAPMIRRORCHECKERDIFFSNAPSHOTS
	EOP_DISALLOWED_ON_BUSY_MIRROR
	EOP_DISALLOWED_ON_LOADSHARING_VOL
	EOP_DISALLOWED_ON_CLONE_PARENT
	EOP_DISALLOWED_ON_BACKUP_ACTIVE_VOL
	EOP_DISALLOWED_ON_STRIPED_VOL
	EOP_DISALLOWED_ON_COMPRESSED_VOL
	EOP_DISALLOWED_ON_7MODE_VOL
	EOP_DISALLOWED_ON_VOL_ALREADY_ON_AGGR
	ESNAPMIRRORUNDELETEDSNAPSHOTONDEST
	ESNAPMIRRORENGINETYPENOTSPECIFIED
	ESNAPMIRRORMISMATCHEDSNAPSHOTLISTS
	ESNAPMIRRORDESTINATIONNOTRESTRICTED
	ESNAPMIRRORDESTINATIONNOTEMPTY
	ESNAPMIRRORNOSNAPLOCKVOLUME
	ESNAPMIRRORNOCOMPRESSEDVOLUME
	ESNAPMIRRORDESTVOLTOOSMALL
	EROOTVOL_NOT_FULLY_GUARANTEED
	EVOL_FRACTIONAL_RESERVE_INVALID_FOR_ROOT
	EVOL_FRACTIONAL_RESERVE_INVALID_FOR_PENDING_ROOT
	EVOL_FRACTIONAL_RESERVE_INVALID_FOR_IRON_ROOT
	EOP_64BIT_UPGRADE_SCANNER_DISABLED
	E_ADDRFAMILY
	E_AGAIN
	E_BADFLAGS
	E_FAMILY
	E_MEMORY
	E_NODATA
	E_NONAME
	E_SERVICE
	E_SOCKTYPE
	E_SYSTEM
	E_BADHINTS
	E_PROTOCOL
	E_NXDOMAIN
	E_RESNULL
	E_MAX
	EDISKASSIGNFAIL
	ENOFMMDEVICES
	EVFILERMONITORNOTSTARTED
	EFCMON_GENERATION
	EFCMON_INVALID_CONFIG
	EVOLMOVEJOBNOTINCUTOVERDEFERRED
	EVOLMOVEJOBSIGNALSENDFAILED
	E_VOL_MOVE_NOT_COMPATIBLE_VERSION
	E_VOL_MOVE_DC_NOT_ALLOWED
	E_OP_DISALLOWED_ON_AGGR_NOT_IN_VSERVER_LIST
	E_OP_UNSUPPORTED_NO_SPACE_ON_DESTINATION_AGGR
	EROLENOTFOUND
	EINVALIDAPPLICATION
	EROLECONFIGNOTFOUND
	EUSERNOTFOUND
	EINVALIDACCESS
	EUSERLOCKFAILED
	EUSERUNLOCKFAILED
	ECMDDIRNOTFOUND
	EINVALIDCMDDIRNAME
	EINVALIDQUERY
	EAPPLICATIONNOTFOUND
	EAUTHENTICATIONMETHODNOTFOUND
	ESTRIPEDVOL_PRIVILEGELEVEL
	EVOLUME_DEST_STRIPED_VOL_NAME_NOT_ALLOWED
	EVOLUME_FLEX_TO_STRIPED_NOT_ALLOWED
	ECANTQUIESCELASTPATH
	EINVALIDTARGET
	ELUNQUIESCING
	ERESUMEFAILED
	EQUIESCEFAILED
	EQUIESCENOTSUPPORTED
	EONTAPI_VOLTRANS_GOINGHOME
	EONTAPI_VOLTRANS_VOLNOTFOUND
	E_DIRECTORY_CHANGED
	EOP_DISALLOWED_ON_SPARSE_VOL
	EOP_DISALLOWED_ON_AGGR_WITH_SPARSE_VOL
	EPARTNERDISKONLY
	EAGGR_MIGRATE_HA_MSG_ERR
	EAGGR_MIGRATE_ONLINE_TIMEOUT
	EAGGR_MIGRATE_ONLINE_FAILED
	EVOLUMENOTLOCAL
	EVOLUME_RELSTATUS_UNKNOWN
	ESNAPMIRRORDBLADEABORT
	ESNAPMIRRORSCANNINGBLOCKMETADATA
	ESNAPMIRROR_REF_OR_XFER_SNAPSHOT_DELETED
	ESNAPMIRRORUNKNOWNFSVERSION
	ESNAPMIRRORJUMPAHEADFAILED
	ECKSUMNOTKNOWN
	ECKSUMTYPEMISMATCH
	EINVENTORYMISMATCH
	EPARENTNOTONLINE
	ESOURCE_ISNOT_LOCAL_VOLUME
	EDEST_ISNOT_LOCAL_VOLUME
	ESOURCE_IS_LS_VOLUME
	ESOURCE_ISNOT_LS_VOLUME
	ESOURCE_DEST_SAME
	ESOURCE_IS_DIFFERENT
	ESOURCE_IS_EXISTING_DEST_VOLUME
	ESOURCE_VOLUME_HAS_CACHE
	ESOURCE_ISNOT_RW_VOLUME
	ESOURCE_IS_STRIPED_VOLUME
	EDEST_ISNOT_LS_VOLUME
	EDEST_IS_EXISTING_SOURCE_VOLUME
	EDEST_IS_EXISTING_DEST_VOLUME
	EDEST_ISNOT_DP_VOLUME
	EDEST_IS_RW_VOLUME
	EDEST_VOLUME_IN_LS_RELATION
	EDEST_VOLUME_NOT_EMPTY
	EDEST_VOLUME_HAS_CACHE
	EDEST_IS_CACHE_VOLUME
	EDEST_VOLUME_NOT_INITIALIZED
	EDEST_IS_STRIPED_VOLUME
	ERELATION_EXISTS
	ENOSNAPSHOT_COPY
	EOP_FROM_NONMGR_VSERVER
	EEMPTY_VOLUMES
	ESCHEDULE_DOESNT_EXIST
	ERELATION_NOT_QUIESCED
	ERELATION_IS_QUIESCED
	ESOURCE_DEST_VSERVERS_DIFFERENT
	ENOTRANSFER_IN_PROGRESS
	EANOTHER_OP_ACTIVE
	EDEST_LS_VOLUME_CURRENT
	EDEST_VOLUME_OFFLINE
	ELS_SET_DEST_VOLUMES_NOT_CURRENT
	ELS_SET_ISNOT_INITIALIZED
	ETRIES_COUNT_IS_ZERO
	ETRANSFER_IN_PROGRESS
	EDEST_MIRROR_ENGINE_INCOMPATIBLE
	ENOCHECK_IN_PROGRESS
	EVOLUMES_WITH_DIFF_STRIPES
	EFAILOVER
	EDEST_IS_LS_VOLUME
	ESIS_CLONE_VFILER_ACCESS
	ESPARSE_TOO_MANY_SPARSE_VOLS
	ESPARSE_VOL_CREATE_FAILED
	ESPARSE_UNKNOWN_PROTOCOL
	ESPARSE_SRC_VOL_UNAVAILABLE
	ESPARSE_SRC_VOL_NOT_FLEX
	ESPARSE_SRC_VOL_WORM
	EVOL_CLONE_BEING_SPLIT
	EVOL_MOVING_PARENT_VOL_RETRY
	EAGGR_READONLY
	EVOL_LOCKED_SNAPSHOTS
	EVOL_SCAN_INIT_FAILED
	EDISKFAILED
	ESNAPMIRRORCLONERESYNCERROR
	E_VOLUME_INACCESSIBLE
	EVOLEXISTS
	ESNAPMIRROR_JOB_INITIATED_ABORT
	ESIS_CLONE_CLONE_SUB_COMPRESSION
	EDEST_IS_VOLUME_CLONE
	ESIS_CLONE_MAX_DENSE_LIMIT_REACHED
	ESPARSE_SRC_VOL_INDEX_DIR
	EDEST_VOL_LOCKED
	ESRC_VOL_LOCKED
	EVOLUME_FS_SIZE_FIXED
	ESNAPMIRRORVMALIGNNOTSUPPORTED
	EVOLUME_IRON_NON_LOCAL_STATUS
	EVOLUME_UNSUPPORTED_OPTION_VMALIGN
	EVOLUME_64BIT_UPGRADE_VVOL_ENOSPC_OVERWRITE
);

use constant EONTAPI_EPERM => 1;
use constant EONTAPI_ENOENT => 2;
use constant EONTAPI_ESRCH => 3;
use constant EONTAPI_EINTR => 4;
use constant EONTAPI_EIO => 5;
use constant EONTAPI_ENXIO => 6;
use constant EONTAPI_E2BIG => 7;
use constant EONTAPI_ENOEXEC => 8;
use constant EONTAPI_EBADF => 9;
use constant EONTAPI_ECHILD => 10;
use constant EONTAPI_EDEADLK => 11;
use constant EONTAPI_ENOMEM => 12;
use constant EONTAPI_EACCES => 13;
use constant EONTAPI_EFAULT => 14;
use constant EONTAPI_ENOTBLK => 15;
use constant EONTAPI_EBUSY => 16;
use constant EONTAPI_EEXIST => 17;
use constant EONTAPI_EXDEV => 18;
use constant EONTAPI_ENODEV => 19;
use constant EONTAPI_ENOTDIR => 20;
use constant EONTAPI_EISDIR => 21;
use constant EONTAPI_EINVAL => 22;
use constant EONTAPI_ENFILE => 23;
use constant EONTAPI_EMFILE => 24;
use constant EONTAPI_ENOTTY => 25;
use constant EONTAPI_ETXTBSY => 26;
use constant EONTAPI_EFBIG => 27;
use constant EONTAPI_ENOSPC => 28;
use constant EONTAPI_ESPIPE => 29;
use constant EONTAPI_EROFS => 30;
use constant EONTAPI_EMLINK => 31;
use constant EONTAPI_EPIPE => 32;
use constant EONTAPI_EDOM => 33;
use constant EONTAPI_ERANGE => 34;
use constant EONTAPI_EAGAIN => 35;
use constant EONTAPI_EINPROGESS => 36;
use constant EONTAPI_EALREADY => 37;
use constant EONTAPI_ENOTSOCK => 38;
use constant EONTAPI_EDESTADDRREQ => 39;
use constant EONTAPI_EMSGSIZE => 40;
use constant EONTAPI_EPROTOTYPE => 41;
use constant EONTAPI_ENOPROTOOPT => 42;
use constant EONTAPI_EPROTONOSUPPORT => 43;
use constant EONTAPI_ESOCKTNOSUPPORT => 44;
use constant EONTAPI_EOPNOTSUPP => 45;
use constant EONTAPI_EPFNOSUPPORT => 46;
use constant EONTAPI_EAFNOSUPPORT => 47;
use constant EONTAPI_EADDRINUSE => 48;
use constant EONTAPI_EADDRNOTAVAIL => 49;
use constant EONTAPI_ENETDOWN => 50;
use constant EONTAPI_ENETUNREACH => 51;
use constant EONTAPI_ENETRESET => 52;
use constant EONTAPI_ECONNABORTED => 53;
use constant EONTAPI_ECONNRESET => 54;
use constant EONTAPI_ENOBUFS => 55;
use constant EONTAPI_EISCONN => 56;
use constant EONTAPI_ENOTCONN => 57;
use constant EONTAPI_ESHUTDOWN => 58;
use constant EONTAPI_ETOOMANYREFS => 59;
use constant EONTAPI_ETIMEDOUT => 60;
use constant EONTAPI_ECONNREFUSED => 61;
use constant EONTAPI_ELOOP => 62;
use constant EONTAPI_ENAMETOOLONG => 63;
use constant EONTAPI_EHOSTDOWN => 64;
use constant EONTAPI_EHOSTUNREACH => 65;
use constant EONTAPI_ENOTEMPTY => 66;
use constant EONTAPI_EPROCLIM => 67;
use constant EONTAPI_EUSERS => 68;
use constant EONTAPI_EDQUOT => 69;
use constant EONTAPI_ESTALE => 70;
use constant EONTAPI_EREMOTE => 71;
use constant EONTAPI_EBADRPC => 72;
use constant EONTAPI_ERPCMSGDENIED => 73;
use constant EONTAPI_EPROGUNAVAIL => 74;
use constant EONTAPI_EPROGMISMATCH => 75;
use constant EONTAPI_EPROCUNAVAIL => 76;
use constant EONTAPI_ENOLCK => 77;
use constant EONTAPI_ENOSYS => 78;
use constant EONTAPI_EFTYPE => 79;
use constant EONTAPI_EMTUTOOBIG => 80;
use constant EONTAPI_EOFFLINE => 81;
use constant EONTAPI_EBADSTREAM => 82;
use constant EONTAPI_EBADSTREAMDIR => 83;
use constant EONTAPI_ELOADCOMPLETE => 84;
use constant EONTAPI_EMOUNTING => 85;
use constant EONTAPI_EWFLUSH => 99;
use constant EONTAPI_EBADPATH => 100;
use constant EONTAPI_EBADCHAR => 101;
use constant EONTAPI_ESHARECONFLICT => 102;
use constant EONTAPI_ELOCKCONFLICT => 103;
use constant EONTAPI_ENOTCOVERED => 104;
use constant EONTAPI_EBADXINODE => 105;
use constant EONTAPI_ENOTXINODE => 106;
use constant EONTAPI_EBADOWNER => 107;
use constant EONTAPI_ERMTWRITELEN => 108;
use constant EONTAPI_EBADRMT => 109;
use constant EONTAPI_EKNOWNBADRMT => 110;
use constant EONTAPI_ERMTEOF => 111;
use constant EONTAPI_EDELPENDING => 112;
use constant EONTAPI_ETRUNCATED => 113;
use constant EONTAPI_EREJECTED => 114;
use constant EONTAPI_EREADONLY => 115;
use constant EONTAPI_EPARTNERREJECT => 116;
use constant EONTAPI_ETOOCOMPLEX => 117;
use constant EONTAPI_EREGX => 118;
use constant EONTAPI_EREGXBADVALUE => 119;
use constant EONTAPI_EPERSISTENCE => 120;
use constant EONTAPI_ESTHREAD => 121;
use constant EONTAPI_EDISABLED => 122;
use constant EONTAPI_ENOTVSCANNED => 123;
use constant EONTAPI_EFABRIC => 124;
use constant EONTAPI_ESYSTEMERR => 125;
use constant EONTAPI_EGSSAPI => 126;
use constant EONTAPI_ERPCGSSSEQNUM => 127;
use constant EONTAPI_EPROXYME => 128;
use constant EONTAPI_ERSRVCONFLICT => 129;
use constant EONTAPI_ERSRVNSUPPORTED => 130;
use constant EONTAPI_ENOQTREE => 131;
use constant EONTAPI_ENOTLOCKED => 132;
use constant EONTAPI_ELOCKCANCELLED => 133;
use constant EONTAPI_ENOSPCSNAP => 134;
use constant EONTAPI_ENOMORESNAPS => 135;
use constant EONTAPI_ERECURSE => 136;
use constant EONTAPI_ERECLAIM => 137;
use constant EONTAPI_EZEROLENREC => 138;
use constant EONTAPI_ENOTFSCREENED => 139;
use constant EONTAPI_EISVDISK => 140;
use constant EONTAPI_EWAFLMSGABORTED => 141;
use constant EONTAPI_EMSGNULLIFY => 142;
use constant EONTAPI_ECOMPRESSCHECK => 143;
use constant EONTAPI_EVOLSMALL => 144;
use constant EONTAPI_EVOLBIG => 145;
use constant EONTAPI_EVOLPAIRED => 146;
use constant EONTAPI_EVOLNOTFLEX => 147;
use constant EONTAPI_EVOLSTALE => 148;
use constant EONTAPI_ENOREG => 149;
use constant EONTAPI_ENOREGKEY => 150;
use constant EONTAPI_ECANNOTDELETE => 151;
use constant EONTAPI_EWORMNOCLOCK => 152;
use constant EONTAPI_EWORMVOLWORM => 153;
use constant EONTAPI_EWORMVOLSLC => 154;
use constant EONTAPI_EWORMVOLNOTWORM => 155;
use constant EONTAPI_EWORMSNAPLOCKED => 156;
use constant EONTAPI_EWORMSNAPRENAME => 157;
use constant EONTAPI_EWORMPERIOD => 158;
use constant EONTAPI_ENOSPCAGGR => 159;
use constant EONTAPI_EVOLOPNOTSUPP => 160;
use constant ESWAPFILENOSPACE => 161;
use constant EONTAPI_EADMINOPQUIESCED => 198;
use constant EONTAPI_EWRONGSTRIPE => 288;
use constant EDATAUNRECOVERABLE => 302;
use constant ECLONEINPROGRESS => 307;
use constant EFILEIO => 1000;
use constant EIPV6 => 1001;
use constant EMODE => 1002;
use constant ENOPARTNERIFC => 1004;
use constant EHOST_BADCONFIGURE => 1005;
use constant EHOST_TRYAGAIN => 1006;
use constant EHOST_MISC => 1007;
use constant ECHECKRESULTS => 1008;
use constant ELOOPBACK => 1009;
use constant ENETMASKINVALID => 1018;
use constant EIOCTLERROR => 1019;
use constant EBROADCASTINVALID => 1020;
use constant EVDISK_ERROR_NOT_IMPLEMENTED => 9000;
use constant EVDISK_ERROR_NOT_QTREE_ROOT => 9001;
use constant EVDISK_ERROR_NOT_VDISK_TYPE => 9002;
use constant EVDISK_ERROR_NO_SUCH_INITGROUP => 9003;
use constant EVDISK_ERROR_INITGROUP_EXISTS => 9004;
use constant EVDISK_ERROR_NOT_VALID_FC_WWN => 9005;
use constant EVDISK_ERROR_NOT_VALID_ISCSI_NAME => 9006;
use constant EVDISK_ERROR_NODE_NOT_IN_INITGROUP => 9007;
use constant EVDISK_ERROR_INITGROUP_HAS_NODE => 9008;
use constant EVDISK_ERROR_LUN_MAPPING_CONFLICT => 9009;
use constant EVDISK_ERROR_INITGROUP_WRONG_TYPE => 9010;
use constant EVDISK_ERROR_NO_SUCH_ATTRIBUTE => 9011;
use constant EVDISK_ERROR_VDISK_EXISTS => 9012;
use constant EVDISK_ERROR_VDISK_EXPORTED => 9013;
use constant EVDISK_ERROR_VDISK_NOT_ENABLED => 9014;
use constant EVDISK_ERROR_VDISK_NOT_DISABLED => 9015;
use constant EVDISK_ERROR_NO_SUCH_LUNMAP => 9016;
use constant EVDISK_ERROR_NO_SUCH_VDISK => 9017;
use constant EVDISK_ERROR_NOT_IN_SAME_QTREE => 9018;
use constant EVDISK_ERROR_SOURCE_IS_VDISK => 9019;
use constant EVDISK_ERROR_NO_SUCH_DIRECTORY => 9020;
use constant EVDISK_ERROR_INVALID_SNAPSHOT_PATH => 9021;
use constant EVDISK_ERROR_NOT_IN_SAME_VOLUME => 9022;
use constant EVDISK_ERROR_INITGROUP_HAS_VDISK => 9023;
use constant EVDISK_ERROR_INITGROUP_HAS_LUN => 9024;
use constant EVDISK_ERROR_INITGROUP_MISSING_ARGS => 9025;
use constant EVDISK_ERROR_INITGROUP_INVALID_ATTR_TYPE => 9026;
use constant EVDISK_ERROR_INITGROUP_INVALID_ATTR_VALUE => 9027;
use constant EVDISK_ERROR_NO_EXPORTED_VDISK_SHARE_WRITE => 9028;
use constant EVDISK_ERROR_INITGROUP_MAPS_EXIST => 9029;
use constant EVDISK_ERROR_VOLUME_NOT_SPACE_RESERVED => 9030;
use constant EVDISK_ERROR_SNAPSHOT_FILE_NOT_VDISK => 9031;
use constant EVDISK_ERROR_NITGROUP_INVALID_ATTR_VALUE_OS_TYPE => 9032;
use constant EVDISK_ERROR_MUST_SPECIFY_F_FLAG => 9033;
use constant EVDISK_ERROR_SIZE_TOO_LARGE => 9034;
use constant EVDISK_ERROR_RESIZE_TOO_LARGE => 9035;
use constant EVDISK_ERROR_NO_SUCH_VOLUME => 9036;
use constant EVDISK_ERROR_USER_ABORT_ACTION => 9037;
use constant EVDISK_ERROR_CLONING => 9038;
use constant EVDISK_ERROR_INITIATOR_HAS_VDISK => 9039;
use constant EVDISK_ERROR_FILE_IS_SPC_RESERVED => 9040;
use constant EVDISK_ERROR_SIZE_TOO_SMALL => 9041;
use constant EVDISK_ERROR_SIZE_UNCHANGED => 9042;
use constant EVDISK_ERROR_NO_SUCH_SNAPSHOT => 9043;
use constant EVDISK_ERROR_IGROUP_NOT_THROTTLED => 9044;
use constant EVDISK_ERROR_IGROUP_ALREDY_THROTTLED => 9045;
use constant EVDISK_ERROR_THROTTLE_TOO_MUHC => 9046;
use constant EVDISK_ERROR_THROTTLE_BEING_DELETED => 9047;
use constant EVDISK_ERROR_NO_SUCH_CLONE => 9048;
use constant EVDISK_ERROR_NO_ISCSI_THROTTLES => 9049;
use constant EVDISK_ERROR_INVALID_ATTR_MODE_VALUE => 9050;
use constant EVDISK_ERROR_INITGROUP_MEMBER_CONFLICTING_OS_TYPES => 9051;
use constant EVDISK_ERROR_INITGROUP_SET_TYPE_CONFLICT => 9052;
use constant EVDISK_ERROR_INITGROUP_MEMBER_VSA_MIXED => 9053;
use constant EVDISK_ERROR_INITGROUP_SET_VSA_CONFLICT => 9054;
use constant EVDISK_ERROR_RESIZE_FIXES_NOT_GEOM_ALIGNED => 9055;
use constant EVDISK_ERROR_RESIZE_VLD_TYPE_LUN_FIXES => 9056;
use constant EVDISK_ERROR_RESIZE_IMGAG_TYPE_LUN_FIXES => 9057;
use constant EVDISK_ERROR_INITGROUP_F_FLAG_REQUIRED => 9058;
use constant EVDISK_ERROR_USE_PARTNER_NOT_APPLICABLE => 9059;
use constant EVDISK_ERROR_RESTORE_WALKOVER_EACHOTHER => 9060;
use constant EVDISK_ERROR_VOLUME_SPARSE => 9061;
use constant EVDISK_ERROR_DESTROY_LUN_BUSY => 9062;
use constant EVDISK_ERROR_CANT_CREATE_INITGROUP_FILE => 9063;
use constant EVDISK_ERROR_CANT_WRITE_INITGROUP_FILE => 9064;
use constant EVDISK_ERROR_CANT_RENAME_INITGROUP_FILE => 9065;
use constant EVDISK_ERROR_CANT_CREATE_VFILER_SHADOW_INITGROUP_FILE => 9066;
use constant EVDISK_ERROR_CANT_WRITE_VFILER_SHADOW_INITGROUP_FILE => 9067;
use constant EVDISK_ERROR_CANT_RENAME_VFILER_SHADOW_INITGROUP_FILE => 9068;
use constant EVDISK_ERROR_INITGROUP_TOO_MANY_NODENAMES => 9069;
use constant EVDISK_ERROR_LUN_MISSING_FROM_SNAPSHOT => 9070;
use constant EVDISK_ERROR_SNAPVALIDATOR_ERROR => 9071;
use constant EVDISK_ERROR_PARTNER_HAS_LUN => 9072;
use constant EVDISK_ERROR_PARTNER_NOT_REACHABLE => 9073;
use constant EVDISK_ERROR_PORTSET_NO_SUCH_SET => 9074;
use constant EVDISK_ERROR_PORTSET_ALREADY_EXIST => 9075;
use constant EVDISK_ERROR_PORTSET_HAS_PORT => 9076;
use constant EVDISK_ERROR_PORTSET_INVALID_PORT_NAME => 9077;
use constant EVDISK_ERROR_PORTSET_TOO_MANY_PORTS => 9078;
use constant EVDISK_ERROR_PORTSET_WRONG_TYPE => 9079;
use constant EVDISK_ERROR_INITGROUP_ALREADY_BOUND => 9080;
use constant EVDISK_ERROR_INITGROUP_NOT_BOUND => 9081;
use constant EVDISK_ERROR_INITGROUP_EMPTY_PSET_BIND => 9082;
use constant EVDISK_ERROR_PORTSET_NO_SUCH_PORT => 9083;
use constant EVDISK_ERROR_PORTSET_NO_SUCH_FILER_NAME => 9084;
use constant EVDISK_ERROR_PARTNER_HAS_DIFFERENT_OS_TYPE => 9085;
use constant EVDISK_ERROR_PARTNER_HAS_DIFFERENT_VSA_SETTING => 9086;
use constant EVDISK_ERROR_PORTSET_CANT_CREATE_FILE => 9087;
use constant EVDISK_ERROR_PORTSET_CANT_WRITE_FILE => 9088;
use constant EVDISK_ERROR_PORTSET_CANT_READ_FILE => 9089;
use constant EVDISK_ERROR_PORTSET_CANT_OPEN_FILE => 9090;
use constant EVDISK_ERROR_LUN_TOO_LARGE => 9091;
use constant EVDISK_ERROR_PORTSET_IC_DOWN => 9092;
use constant EVDISK_ERROR_CLONE_NOT_SPLITTING => 9093;
use constant EVDISK_ERROR_LUN_HAS_NO_SERIAL_NO => 9095;
use constant EVDISK_ERROR_PORTSET_THROTTLE_EXCEEDED => 9096;
use constant EVDISK_ERROR_PORTSET_CANT_DESTROY_BOUND_PORTSET => 9097;
use constant EVDISK_ERROR_CFMODE_MISMATCH => 9098;
use constant EVDISK_ERROR_PORTSET_NOT_VALID_CFMODE => 9099;
use constant EVDISK_ERROR_CANNOT_CHANGE_SPCRES_DURING_SPLIT => 9100;
use constant EVDISK_ERROR_INITGROUP_BIND_WRONG_TYPE => 9101;
use constant EVDISK_ERROR_DB_BAD_INDEX => 9102;
use constant EVDISK_ERROR_DB_NO_SUCH_DATABASE => 9103;
use constant EVDISK_ERROR_ALUA_NOT_SUPPORTED_ON_ISCSI => 9104;
use constant EVDISK_ERROR_ALUA_NOT_SUPPORTED_ON_CFMODE => 9105;
use constant EVDISK_ERROR_PORTSET_INVALID_PARTNER_PORT_NAME => 9110;
use constant EVDISK_ERROR_PORTSET_BOTH_INVALID_PORT_NAMES => 9111;
use constant EVDISK_ERROR_PARTNER_WWNN_MISMATCH_FOR_SSI => 9112;
use constant EVDISK_ERROR_INVALID_DEVICE_ID => 9113;
use constant EVDISK_ERROR_WWPN_ALIAS_NOT_FOUND => 9114;
use constant EVDISK_ERROR_WWPN_ALIASES_NOT_SET => 9115;
use constant EVDISK_ERROR_WWPN_ALIASES_TOO_MANY => 9116;
use constant EVDISK_ERROR_WWPN_ALIAS_INVALID => 9117;
use constant EVDISK_ERROR_QTREE_PRESERVE_FAILED => 9118;
use constant EVDISK_ERROR_QTREE_RESTORE_FAILED => 9119;
use constant EVDISK_ERROR_QTREE_CLEANUP_FAILED => 9120;
use constant EVDISK_ERROR_PREFIX_SUFFIX_SIZE_MISMATCH => 9121;
use constant EVDISK_ERROR_ALUA_ISCSI_TRANSPORT_TYPE_CONFLICT => 9122;
use constant EVDISK_ERROR_ALUA_FCP_TRANSPORT_TYPE_CONFLICT => 9123;
use constant EVDISK_ERROR_LUN_HAS_ALUA_ENABLED_ISCSI_IGROUP => 9124;
use constant EVDISK_ERROR_LUN_HAS_ALUA_ENABLED_FCP_IGROUP => 9125;
use constant EVDISK_ERROR_LUN_HAS_ISCSI_IGROUP => 9126;
use constant EVDISK_ERROR_LUN_HAS_FCP_IGROUP => 9127;
use constant EVDISK_ERROR_LUN_HAS_ALUA_CONFLICTS => 9128;
use constant EVDISK_ERROR_PORTSET_TOO_FEW_PORTS => 9129;
use constant EVDISK_ERROR_WWPN_NOT_FOUND => 9130;
use constant EVDISK_ERROR_WWPN_ALIAS_REMOVE_INVALID_NUM_ARGS => 9131;
use constant EVDISK_ERROR_IN_TAKEOVER => 9132;
use constant EVDISK_ERROR_WWPN_ALIAS_ALREADY_SET => 9133;
use constant EVDISK_ERROR_VOLUMES_ONLINING => 9134;
use constant EVDISK_ERROR_VIRTUAL_LUN_MAPPING_CONFLICT => 9140;
use constant EVDISK_ERROR_LUN_STREAM_DATAUNRECOVERABLE => 9144;
use constant EVDISK_ERROR_VDISK_NOT_STOPPED => 9146;
use constant EVDISK_ERROR_INVALID_PREFIX_SIZE => 9147;
use constant EVDISK_ERROR_INVALID_SUFFIX_SIZE => 9148;
use constant EAPIERROR => 13001;
use constant EAPIAUTHENTICATION => 13002;
use constant EAPIPRIVILEDGE => 13003;
use constant EAPIPRIVILEGE => 13003;
use constant EAPIEXCEPTION => 13004;
use constant EAPINOTFOUND => 13005;
use constant EAPIMISSINGARGUMENT => 13006;
use constant EAPINOTIMPLEMENTED => 13007;
use constant EAPILICENSE => 13008;
use constant EAPIINDEXTOOLARGE => 13009;
use constant EAPIUNSUPPORTEDVERSION => 13010;
use constant EAPITRANSMISSION => 13011;
use constant EOPNOTSUPPORTED => 13012;
use constant EALREADYSTARTED => 13013;
use constant ENOTSTARTED => 13014;
use constant ESERVICENOTSTOPPED => 13015;
use constant ENOTWHILEWAITINGFORGIVEBACK => 13016;
use constant ENOTINMAINTMODE => 13017;
use constant ENOTINREADONLYMODE => 13018;
use constant EAPITOOMANYENTRIES => 13019;
use constant ESNAPSHOTEXISTS => 13020;
use constant ESNAPSHOTDOESNOTEXIST => 13021;
use constant ESNAPSHOTTOOMANY => 13022;
use constant ESNAPSHOTNOTALLOWED => 13023;
use constant ESNAPSHOTBUSY => 13024;
use constant ESNAPSHOTNOSPACE => 13025;
use constant EDUPLICATEDSID => 13026;
use constant EINVALIDDSID => 13027;
use constant EINVALIDMSID => 13028;
use constant EAMBIGUOUS_DSID => 13029;
use constant ESNAPSHOT_NOT_LATEST => 13030;
use constant ESTRIPEDRESTOREOPNOTFOUND => 13037;
use constant EVOLUMESNAPRESTOREERROR => 13038;
use constant EVOLUMEQUIESCED => 13039;
use constant EVOLUMEDOESNOTEXIST => 13040;
use constant EVOLUMEMOUNTING => 13041;
use constant EVOLUMEOFFLINE => 13042;
use constant EVOLUMEREADONLY => 13043;
use constant EVOLUMENAMEINVALID => 13044;
use constant EVOLUMERGSIZEINVALID => 13045;
use constant EVOLUMELANGUAGEINVALID => 13046;
use constant EVOLUMEDISKSIZEINVALID => 13047;
use constant EVOLUMEDISKDUP => 13048;
use constant EVOLUMERGINVALID => 13049;
use constant EQUOTAPARSEERROR => 13050;
use constant EQUOTAINVALID => 13051;
use constant EQUOTAEXISTS => 13052;
use constant EQUOTADOESNOTEXIST => 13053;
use constant EQUOTADIRECTIVE => 13054;
use constant EAPI_CONNECTION => 13055;
use constant EAPI_CONNECTION_DROPPED => 13056;
use constant EAPI_RECEPTION => 13057;
use constant EVOL_NOT_OFFLINE => 13058;
use constant EVOL_NOT_RESTRICTED => 13059;
use constant EVOL_ONLINE => 13060;
use constant EVOL_RESTRICTED => 13061;
use constant EVOL_SPACE_FOR_GUARANTEE => 13062;
use constant EVOL_TOO_MANY => 13063;
use constant EVOLUME_NOT_QUIESCED => 13064;
use constant EVOLUME_CLEAR_QUIESCE => 13065;
use constant EVOLUME_ALREADY_QUIESCED_SET => 13066;
use constant EVOLUME_ALREADY_QUIESCED_CLEAR => 13067;
use constant EVOL_CIFS_OPENS => 13068;
use constant EVOL_INVALID_FSINFO => 13069;
use constant EVFILEROPNOTALLOWED => 13070;
use constant EVFILERNOTFOUND => 13071;
use constant EVFILEROPNOTCOMPLETED => 13072;
use constant EIPSPACENOTFOUND => 13073;
use constant EVOL_UNKNOWN_VERSION => 13074;
use constant EVOL_CIFS_ENABLED => 13075;
use constant EQTREEEXISTS => 13080;
use constant EQTREENOTOWNER => 13081;
use constant EQTREEMAX => 13082;
use constant ECMSINVALIDREQUEST => 13090;
use constant ECMSNOTENABLED => 13091;
use constant ECMSPROCESSINGERROR => 13092;
use constant ESNAPMIRROROFF => 13100;
use constant ESNAPMIRRORPARSERERROR => 13101;
use constant ESNAPMIRRORERROR => 13102;
use constant EISCSISECINVALIDAUTHTYPE => 13109;
use constant EISCSISECINVALIDINPUTERROR => 13110;
use constant EISCSISECPROCESSINGERROR => 13111;
use constant EISCSISECINITNOTFOUNDERROR => 13112;
use constant EFILENOTFOUND => 13113;
use constant EINTERNALERROR => 13114;
use constant EINVALIDINPUTERROR => 13115;
use constant ESETSPCRESERROR => 13116;
use constant EADAPTERNOTFOUND => 13122;
use constant EADAPTERPARTNER => 13123;
use constant EADAPTERINVALIDTYPE => 13125;
use constant ENOADAPTERPARTNER => 13126;
use constant ENOVIRTUALADAPTERS => 13127;
use constant ENOTCLUSTERED => 13128;
use constant ECLUSTERED => 13129;
use constant EDISKNOTFOUND => 13150;
use constant ESWAPINPROGRESS => 13151;
use constant ENOTDISKOWNER => 13152;
use constant EDISKINRAIDZEROVOL => 13153;
use constant EDISKISSPARE => 13154;
use constant EVOLUMEPLEXINVALID => 13155;
use constant EVOLUMEINUSE => 13156;
use constant EVOLUMENOTONLINE => 13157;
use constant EVOLUMEBUSY => 13158;
use constant EVOLUMECIFSTERMINATE => 13159;
use constant EVOLUMECREATING => 13160;
use constant ECLIENTSTATSVFILER => 13161;
use constant ECLIENTSTATSNOTENABLED => 13162;
use constant ENOACTIVECLIENTS => 13163;
use constant ECIFSNOTCONFIGURED => 13164;
use constant EDNSNOTENABLED => 13165;
use constant EHOSTNOTFOUND => 13166;
use constant ELDAPSVRNOTFOUND => 13167;
use constant EVOL_ONLINE_ERROR => 13168;
use constant EVOL_PARTIAL => 13169;
use constant EVOLNOTCLONE => 13170;
use constant EVOLOPNOTUNDERWAY => 13171;
use constant EVOLUME_NOT_QUIESCED_MISSING_PARAMS => 13172;
use constant EVOLUME_NOT_QUIESCED_NOMORE_SNAPSHOTS => 13173;
use constant EVOLUME_NOT_QUIESCED_SNAP_CREATE_BUSY => 13174;
use constant EVOLUME_NOT_QUIESCED_TIMEDOUT => 13175;
use constant EVOLUME_NOT_QUIESCED_PENDING_VOL_REFS => 13176;
use constant EVOLUME_NOT_QUIESECED_PENDING_SNAP_REFS => 13177;
use constant EVOLUME_NOT_QUIESCED_PENDING_MSGS => 13178;
use constant EVOLUME_NOT_QUIESCED_CP_SYNC_TIMEDOUT => 13179;
use constant EVOLUME_NOT_QUIESCED_SNAPSHOT_EXISTS => 13180;
use constant EVOLUME_NOT_QUIESCED_SNAP_SCHED_ABORT_TIMEDOUT => 13181;
use constant EVOLUME_NOT_QUIESCED_ZOMBIE_DRAIN_TIMEDOUT => 13182;
use constant EVOLUME_NOT_QUIESCED_SNAP_CREATE_TIMEDOUT => 13183;
use constant EVOLUME_NOT_QUIESCED_CLONE_FROM_SNAPSHOT_EXISTS => 13184;
use constant EVOLUME_NOT_QUIESCED_CANT_CREATE_SNAPSHOT => 13185;
use constant EVOLUME_NOT_QUIESCED_CANT_CREATE_SNAPSHOT_NO_SPACE => 13186;
use constant ESVCDISABLED => 13200;
use constant ESVCNOTAVAIL => 13201;
use constant ESHAREACCESSDENIED => 13202;
use constant ESHAREEXISTS => 13203;
use constant ESHARETOOMANY => 13204;
use constant ECIFSSHARINGVIOLATION => 13210;
use constant ESANOWNNOTENABLED => 13210;
use constant EINVALIDHOST => 13211;
use constant EINVALIDOWNERID => 13212;
use constant EINVALIDOWNER => 13213;
use constant EINVALIDPASSWORD => 13214;
use constant EEXPORTSINCOMPATIBLE => 13215;
use constant EINODENUMBERTOOSMALL => 13216;
use constant EINODENUMBERTOOLARGE => 13217;
use constant EINVALIDINODE => 13218;
use constant EINELIGIBLEINODE => 13219;
use constant EPARENTINFONOTLOADED => 13220;
use constant EI2PNOTENABLED => 13221;
use constant EVV_COMMON => 13222;
use constant ECIFS_LOGIN_FAILED => 13250;
use constant ECIFS_BIND_FAILED => 13251;
use constant ECIFS_DNS_REQUIRED => 13252;
use constant ECIFS_KRB_CONFLICT => 13253;
use constant ECIFS_AD_CLOCK_SKEW => 13254;
use constant ECIFS_AD_RESET_REQUIRED => 13255;
use constant ECIFS_LIST_UNAVAILABLE => 13256;
use constant ECIFS_DC_CONNECT_FAILED => 13257;
use constant ECIFS_HAVE_SESSION_SCOPED_LOCKS => 13258;
use constant ECIFS_PASSWD_AND_GROUP_REQUIRED => 13259;
use constant ECIFS_SETUP_CANNOT_WRITE => 13260;
use constant EEMS_INVOKE_FAILED => 13301;
use constant EEMS_INVOKE_BAD_PARAM => 13303;
use constant EEMS_INVOKE_ID_BAD => 13310;
use constant EEMS_INVOKE_SEVERITY_REQUIRED => 13311;
use constant EEMS_INVOKE_SEVERITY_INVALID => 13312;
use constant EEMS_INVOKE_SEVERITY_NOT_VARIABLE => 13313;
use constant EEMS_INVOKE_PARAMS_INSUFFICIENT => 13314;
use constant EEMS_INVOKE_VERSION_INVALID => 13315;
use constant EEMS_INVOKE_SUPRESS_DUP => 13316;
use constant EEMS_INVOKE_SUPRESS_TIMER => 13317;
use constant EEMS_INVOKE_NVRAM_TOO_BIG => 13318;
use constant EEMS_INVOKE_QUEUE_FULL => 13319;
use constant EREALLOCATE_EXISTS => 13501;
use constant EREALLOCATE_BADPATH => 13502;
use constant EREALLOCATE_NOMEM => 13503;
use constant EREALLOCATE_NOSCAN => 13504;
use constant EREALLOCATE_BADVOL => 13505;
use constant EREALLOCATE_READONLY => 13506;
use constant EREALLOCATE_BADSCHED => 13507;
use constant EREALLOCATE_OFF => 13508;
use constant EREALLOCATE_SNAPSHOT => 13509;
use constant EDISKNOTSPARE => 13510;
use constant EDISKTOOSMALL => 13511;
use constant ERAIDGROUPDEGRADED => 13512;
use constant ESAVECOREDISK => 13513;
use constant EINVALIDSTATE => 13514;
use constant ECANT_USE_ALL_DISKS => 13515;
use constant ENPMINVPLOC => 13600;
use constant ENPMNOPKG => 13601;
use constant ENPMNOMETA => 13602;
use constant ENPMERXMETA => 13603;
use constant EINCRCOPYFAILED => 13604;
use constant EINCRCOPYOPNOTFOUND => 13605;
use constant EINCRCOPYINVALIDUUID => 13606;
use constant EINCRCOPYINVALIDOP => 13607;
use constant EINCRCOPYNOMEM => 13608;
use constant EINCRCOPYINVALIDINPUT => 13609;
use constant EINCRCOPYINVALIDOPTYPE => 13610;
use constant EINCRCOPYDUPLICATESESSION => 13611;
use constant EINCRCOPYNOTSUPPORT => 13612;
use constant EINCRCOPYVOLOFFLINE => 13613;
use constant EINCRCOPYVOLNOTFOUND => 13614;
use constant EINCRCOPYSNAPCREATIONFAIL => 13615;
use constant EINCRCOPYSNAPSHOTEXIST => 13616;
use constant EINCRCOPYNOSTREAMESTABLISHED => 13617;
use constant EINCRCOPYAGAIN => 13618;
use constant EINCRCOPY_CSM_CALL_FAIL => 13619;
use constant EINCRCOPY_CSM_SEND_FAIL => 13620;
use constant EINCRCOPY_CSM_CANT_GET_SESSION => 13621;
use constant EINCRCOPY_CSM_CANT_REGISTER_SENDCB => 13622;
use constant EDSIDPARSEERROR => 13623;
use constant EINCRCOPY_SET_INCORE_QUIESCE_VOL_FAIL => 13624;
use constant EINCRCOPY_UNSET_INCORE_QUIESCE_VOL_FAIL => 13625;
use constant EINCRCOPY_SET_ONDISK_QUIESCE_VOL_FAIL => 13626;
use constant EVOLMOVE_NDMP_DUMPS_RUNNING => 13627;
use constant EINCRCOPY_DUMPS_RUNNING => 13627;
use constant EVOLMOVE_NDMP_RESTORE_RUNNING => 13628;
use constant EINCRCOPY_RESTORE_RUNNING => 13628;
use constant EVOLMOVE_SIS_UNDO_RUNNING => 13629;
use constant EVOLMOVE_WAFL_ERR => 13630;
use constant EVOLMOVE_AGENT_IS_INITIALIZING => 13631;
use constant EVOLMOVE_LOCKED_FOR_SNAPMIRROR => 13632;
use constant ECGERROR => 13700;
use constant ECGSNAPERR => 13701;
use constant ECGOFF => 13702;
use constant ECHARMAP_INVALID => 13800;
use constant ECHARMAP_NO_PERSIST => 13801;
use constant ETOERRMIN => 13900;
use constant ESERVICENOTINITIALIZED => 13901;
use constant ESERVICENOTLICENSED => 13902;
use constant ESERVICENOTENABLED => 13903;
use constant EMBOXDEGRADED => 13904;
use constant EMBOXUNKNOWN => 13905;
use constant EMBOXVERSIONMISMATCH => 13906;
use constant EPARTNERDISABLEDTO => 13907;
use constant EOPERATORDENY => 13908;
use constant ENVRAMSIZEMISMATCH => 13909;
use constant EVERSIONMISMATCH => 13910;
use constant EINTERCONNECTERROR => 13911;
use constant EPARTNERBOOTING => 13912;
use constant ESHELFHOT => 13913;
use constant EPARTNERREVERT => 13914;
use constant ELOCALREVERT => 13915;
use constant EPARTNERTRYINGTAKEOVER => 13916;
use constant ETAKEOVERINPROGRESS => 13917;
use constant EHALTNOTAKEOVER => 13918;
use constant EUNSYNCNVRAM => 13919;
use constant EUNKNOWNTAKEOVERERROR => 13920;
use constant EWAITINGFORPARTNER => 13921;
use constant ELOWMEMORY => 13922;
use constant EHALTING => 13923;
use constant EMBOXUNCERTAIN => 13924;
use constant ENOAUTOTAKEOVER => 13925;
use constant EPARTNERNOTWAITING => 13926;
use constant ENOAGGRS => 13927;
use constant EOP_DISALLOWED_DURING_GIVEBACK => 13928;
use constant EOP_DISALLOWED_BRINGING_OFFLINE => 13929;
use constant EOP_DISALLOWED_BRINGING_ONLINE => 13930;
use constant EOP_DISALLOWED_DURING_DESTROY => 13931;
use constant EOP_DISALLOWED_VOLUME_FENCED => 13932;
use constant EOP_DISALLOWED_VOLUME_FROZEN => 13933;
use constant EOP_DISALLOWED_VOLUME_OLDLABELS => 13934;
use constant EOP_DISALLOWED_VOLUME_NEEDED_LAZY_SPCRSRV => 13936;
use constant ENOPARTNERINVENTORY => 13937;
use constant EPARTNERMISSINGDISKS => 13938;
use constant ENOTHINGTOTAKEOVER => 13945;
use constant ESENDHOMEINPROGRESS => 13946;
use constant ENVRAMDOWN => 13947;
use constant EINTERCONNECTRESET => 13948;
use constant EBADOPTIONS => 13949;
use constant ENOTHALTED => 13950;
use constant EREVERTINPROGRESS => 13951;
use constant ESERVICEENABLED => 13952;
use constant EINTAKEOVER => 13953;
use constant ETOERRMAX => 13954;
use constant EOPLOCKRECALLFAILED => 13955;
use constant EOP_DISALLOWED_DURING_REVERT => 13956;
use constant EVOLUME_ADMINOP_NOT_FENCED => 13957;
use constant EINVALIDRESERVATION => 14000;
use constant ENODISKSFOUND => 14001;
use constant EMUSTBEINMAINTMODE => 14002;
use constant EFILEEXISTS => 14003;
use constant EJUNCTIONEXISTS => 14004;
use constant EJUNCTIONDOESNOTEXIST => 14005;
use constant EBADFILELENGTH => 14006;
use constant EFILER_NOT_HEALTHY => 14007;
use constant EBADCOREID => 14100;
use constant ECOREDUMPBUSY => 14101;
use constant ECOREDUMPNOTINITIALIZED => 14102;
use constant ESESNOTREADY => 14200;
use constant ESESBUSY => 14201;
use constant ERDB_HA_SF_NOT_INITIALIZED => 14300;
use constant ERDB_HA_ID_MISMATCH => 14301;
use constant ERDB_HA_CONFIGURED => 14302;
use constant ERDB_HA_PARTIALLY_CONFIGURED => 14303;
use constant ERDB_HA_NOT_CONFIGURED => 14304;
use constant ERDB_HA_CONFIG_UUID_MISMATCH => 14305;
use constant ERDB_HA_CANNOT_EXIT_CONFIG => 14306;
use constant ERDB_HA_IO_ERROR => 14307;
use constant ERDB_HA_INVALID_SLOT => 14308;
use constant ERDB_HA_OLD_COOKIE => 14309;
use constant ERDB_HA_INVALID_INPUT => 14310;
use constant ERDB_HA_FAILURE => 14311;
use constant ERDB_HA_ILLEGAL_SLOT_CONTENT => 14312;
use constant ERDB_HA_SLOT_UUID_MISMATCH => 14313;
use constant ERDB_HA_QUIESCENT_PERIOD => 14314;
use constant EFIJIINVALID => 14401;
use constant EFIJIINVALIDEXPR => 14402;
use constant EFIJINOFILTER => 14403;
use constant EFIJIMAXFILTERS => 14404;
use constant EAGGRDOESNOTEXIST => 14420;
use constant EAGGRNOTONLINE => 14421;
use constant EAGGRFAILINGOVER => 14422;
use constant EAGGRMISMATCH => 14423;
use constant ENFS_CLIENT_STATS_NOT_ENABLED => 14424;
use constant ELOOPUNAVAILABLE => 14425;
use constant ESNAPSHOTEXISTSPARTIAL => 14426;
use constant ESNAPVAULTERR => 14450;
use constant ESNAPVAULTSETUP => 14451;
use constant ESNAPVAULTRESOURCE => 14452;
use constant ESNAPVAULTBUSY => 14453;
use constant EVOLUME_NOT_QUIESCED_NOT_MOUNTED => 14460;
use constant EVOLUME_NOT_QUIESCED_ROOT_VOLUME => 14461;
use constant EVOLUME_NOT_QUIESCED_NOT_FLEX => 14462;
use constant EVOLUME_NOT_QUIESCED_IRONING => 14463;
use constant EVOLUME_NOT_QUIESCED_GOING_HOME => 14464;
use constant EVOLUME_NOT_QUIESCED_CB_TIMEOUT => 14465;
use constant EVOLUME_NOT_QUIESCED_NOT_DRAIN => 14466;
use constant EVOLUME_NOT_QUIESCED_FOR_CORAL => 14467;
use constant EVOLAGGRISIRONING => 14468;
use constant EVOLUME_HAS_VFILER_STORAGE => 14469;
use constant EVOLUME_QUIESCING => 14470;
use constant EVOLUME_NOT_BOOLEAN_VALUE => 14471;
use constant EVOLUME_TYPE_NOT_SUPPORTED => 14472;
use constant EVOLISGRIDIRONING => 14473;
use constant EONTAPI_ESNAPDIFF_FILENAME_UNAVAILABLE => 14474;
use constant EVOLUME_NOT_QUIESCED_SAN_NOTIFICATION_TIMEOUT => 14475;
use constant EONTAPI_ESNAPDIFF_FILETYPE_MODIFIED => 14476;
use constant ELOGROTATIONACTIVE => 14499;
use constant ESNAPDIFFINTERROR => 14500;
use constant ESNAPDIFFINVINPUT => 14501;
use constant ESNAPDIFFINVSNAPSHOT => 14502;
use constant ESNAPDIFFSNAPSHOTCHANGED => 14503;
use constant ESNAPDIFFSNAPSHOTEARLIER => 14504;
use constant ESNAPDIFFMAXSESSIONSEXCEEDED => 14506;
use constant ESNAPDIFFDUPLICATESESSION => 14507;
use constant ESNAPDIFFINVALIDSESSION => 14508;
use constant ESNAPDIFFNOI2P => 14509;
use constant ESNAPDIFFVOLOFFLINE => 14510;
use constant ESNAPDIFFABORTED => 14511;
use constant EVOLUMEGSMINVALID => 14512;
use constant EAPIMISSINGOUTPUT => 14513;
use constant EINVALIDOUTPUTERROR => 14514;
use constant EVOLUMECOMPRESSED => 14515;
use constant EVOLUMENOTDECOMPRESSING => 14516;
use constant ENOTIMEZONESET => 14517;
use constant ENOTIMEZONEVERSION => 14518;
use constant EINVALIDTIMEZONE => 14519;
use constant ETIMEZONEDIFFERENTINRC => 14520;
use constant ESNAPLOCKNOTLICENSED => 14521;
use constant ECOMPLIANCECLOCKNOTSET => 14522;
use constant ETAKENOVER => 14523;
use constant EDATENOTSETONPARTNER => 14524;
use constant ERSHSESSIONERROR => 14525;
use constant ERSHKILLERROR => 14526;
use constant EDENSE_REVERTING => 14527;
use constant EDENSE_IRON_RUNNING => 14528;
use constant EDENSE_CLONE_SFSR_INPROG => 14529;
use constant EDENSE_NLCSR_INPROG => 14530;
use constant EDENSE_VOL_NONEXIST => 14531;
use constant EDENSE_VOL_OFFLINE => 14532;
use constant EDENSE_VOL_NOTSUP => 14533;
use constant EDENSE_VOL_RDONLY => 14534;
use constant EDENSE_VOL_TRANSITING => 14535;
use constant EDENSE_VOL_RESTRICTED => 14536;
use constant EDENSE_SNAPSHOT_CREATE => 14537;
use constant EDENSE_SNAPSHOT_DELETE => 14538;
use constant EDENSE_SNAPSHOT_NONEXIST => 14539;
use constant EDENSE_STALE_DINODE => 14540;
use constant EDENSE_STALE_RINODE => 14541;
use constant EDENSE_STALE_DBUF => 14542;
use constant EDENSE_STALE_RBUF => 14543;
use constant EDENSE_CIFS_HOLE_RERVD => 14544;
use constant EDENSE_DONOR_TOO_SMALL => 14545;
use constant EDENSE_RECIPIENT_TOO_SMALL => 14546;
use constant EDENSE_NO_SPACE => 14547;
use constant EDENSE_SHUTDOWN => 14548;
use constant EDENSE_FAILOVER => 14549;
use constant EDENSE_DONOR_RANGE => 14550;
use constant EDENSE_RECPT_RANGE => 14551;
use constant EDENSE_QUOTA_CHECK => 14552;
use constant EDENSE_UNSUPPORTED_VOLTYPE => 14553;
use constant EDENSE_CLONE_SPLITTING => 14554;
use constant EDENSE_CLONE_STOPPED => 14555;
use constant EDENSE_CLONE_SFILE_NONEXIST => 14556;
use constant EDENSE_CLONE_CFILE_NONEXIST => 14557;
use constant EDENSE_CLONE_NO_SLOT => 14558;
use constant EDENSE_CLONE_NO_ARGS => 14559;
use constant EDENSE_CLONE_DIFF_VOLUME => 14560;
use constant EDENSE_CLONE_SAME_FILE => 14561;
use constant EDENSE_CLONE_VOL_REVERTING => 14562;
use constant EDENSE_CLONE_IN_PROG => 14563;
use constant EDENSE_CLONE_SNAPNAME => 14564;
use constant EDENSE_CLONE_SNAPPATH => 14565;
use constant EDENSE_CLONE_SNAP_FH => 14566;
use constant EDENSE_CLONE_SNAP_ATTR => 14567;
use constant EDENSE_CLONE_SFILE_ATTR => 14568;
use constant EDENSE_CLONE_CFILE_ATTR => 14569;
use constant EDENSE_CLONE_EXIST => 14570;
use constant EDENSE_CLONE_METAFILE => 14571;
use constant EDENSE_CLONE_METAFILE_FH => 14572;
use constant EDENSE_CLONE_METAFILE_WRITE => 14573;
use constant EDENSE_CLONE_METAFILE_ATTR => 14574;
use constant EDENSE_CLONE_METAFILE_READ => 14575;
use constant EDENSE_CLONE_SFILE_READ => 14576;
use constant EDENSE_CLONE_CFILE_WRITE => 14577;
use constant EDENSE_CLONE_FH => 14578;
use constant EDENSE_CLONE_CREATE => 14579;
use constant EDENSE_CLONE_SETATTR => 14580;
use constant EDENSE_CLONE_SOURCE_FH => 14581;
use constant EDENSE_CLONE_NOT_SUPP => 14582;
use constant EDENSE_CLONE_PROC => 14583;
use constant EDENSE_CLONE_TYPE_SUPP => 14584;
use constant EDENSE_CLONE_SRC_OUTOF_RANGE => 14585;
use constant EDENSE_CLONE_DEST_OUTOF_RANGE => 14586;
use constant EDENSE_CLONE_OVERLAP_RANGE => 14587;
use constant EDENSE_CLONE_INVALID_RANGE => 14588;
use constant EDENSE_CLONE_RUNNING_OP => 14589;
use constant EDENSE_CLONE_NOT_RUNNING => 14590;
use constant EDENSE_CLONE_NO_OP => 14591;
use constant EDENSE_CLONE_NOT_FAILED => 14592;
use constant EDENSE_CLONE_DEL_INFO => 14593;
use constant EDENSE_CLONE_PENDING_SNAP => 14594;
use constant EDENSE_CLONE_SPLIT_MAP => 14595;
use constant EDENSE_CLONE_INVALID_SOURCE => 14596;
use constant EDENSE_CLONE_INVALID_CLONE => 14597;
use constant EDENSE_CLONE_SNAP_DEL => 14598;
use constant EDENSE_CLONE_GET_SNAPID => 14599;
use constant EDENSE_CLONE_SMALL_DATA => 14600;
use constant EDENSE_VDISK_INVALID_NAME => 14601;
use constant EDENSE_VDISK_NOT_IN_QTREE_ROOT => 14602;
use constant EDENSE_VDISK_VOL_SPARSE_WO_SCSI => 14603;
use constant EDENSE_VDISK_INTERNAL_ERROR => 14604;
use constant EDENSE_VDISK_INVALID_FH => 14605;
use constant EDENSE_VDISK_NO_SUCH_VDISK => 14606;
use constant EDENSE_VDISK_LBA_OFFSET_MISALIGNED => 14607;
use constant EDENSE_VDISK_SRC_INVALID_BLOCK_RANGE => 14608;
use constant EDENSE_VDISK_DST_INVALID_BLOCK_RANGE => 14609;
use constant EDENSE_VDISK_SRC_LUN_CLONE => 14610;
use constant EDENSE_CLONE_MAX_OPS_VOL => 14611;
use constant EDENSE_CLONE_INVALID_DIR => 14612;
use constant EDENSE_CLONE_NOT_QTREE_ROOT => 14613;
use constant EDENSE_CLONE_LARGE_INFO => 14614;
use constant EDENSE_CLONE_INVALID_ID => 14615;
use constant EDENSE_CLONE_NOT_LICENSED => 14616;
use constant EDENSE_CLONE_LICENSE_EXPIRED => 14617;
use constant EDENSE_CLONE_FILE_FOLD_INPROG => 14618;
use constant EDENSE_CLONE_WORM_VOL => 14619;
use constant EDENSE_CLONE_INVALID_UUID => 14620;
use constant EDENSE_CLONE_EXISTING_OP => 14621;
use constant EDENSE_CLONE_CHANGELOG_OFF => 14622;
use constant EDENSE_NON_SUPPORTED_PLATFORM => 14623;
use constant EDENSE_STALE_CLONE_DIR_INODE => 14624;
use constant EDENSE_CLONE_DIR_FH => 14625;
use constant EDENSE_CLONE_MAX_OPS_FILER => 14626;
use constant EDENSE_CLONE_METAFILE_VER_MISMATCH => 14627;
use constant EDENSE_UNKNOWN => 14628;
use constant EROUTEEXISTS => 14629;
use constant EINVALIDROUTE => 14630;
use constant EROUTENOTFOUND => 14631;
use constant EVLANEXISTS => 14632;
use constant EINTERFACENOTFOUND => 14634;
use constant EIPSPACEEXISTS => 14635;
use constant EIPSPACEDOESNOTEXIST => 14636;
use constant EDENSE_CLONE_MAX_OPS_VFILER => 14637;
use constant EDENSE_CLONE_SRC_VFACCESS => 14638;
use constant EDENSE_CLONE_DST_VFACCESS => 14639;
use constant EDENSE_CLONE_VFILER_NOT_RUNNING => 14640;
use constant EDENSE_VFILER_CUTOVER => 14641;
use constant EDISKTYPEWRONGFORSNAPLOCK => 14700;
use constant EDISKTYPEWRONGFORVOL => 14701;
use constant EDISK_TYPE_MISMATCH => 14702;
use constant EVOL_ALREADY_MOUNTED => 14713;
use constant EVOL_MOUNT_FAILED => 14714;
use constant EJUNCTION_CREATE_FAILED => 14715;
use constant EVOL_NOT_MOUNTED => 14716;
use constant EVOL_UNMOUNT_FAILED => 14717;
use constant EJUNCTION_DELETE_FAILED => 14718;
use constant EVSERVER_OP_NOT_ALLOWED => 14719;
use constant EDENSE_COMP_SCAN_ACTIVE => 14900;
use constant EDENSE_CLONE_SUB_COMPRESSION => 14901;
use constant EDENSE_CLONE_DECOMP_ACTIVE => 14902;
use constant EINVALIDPATH => 14920;
use constant EVSERVERNAMEEXISTS => 14922;
use constant EVSERVERALREADYSTARTED => 14923;
use constant EVSERVERNOTRUNNING => 14924;
use constant ESIS_CLONE_VOL_NONEXIST => 14925;
use constant ESIS_CLONE_VOL_OFFLINE => 14926;
use constant ESIS_CLONE_VOL_NOTSUP => 14927;
use constant ESIS_CLONE_VOL_RDONLY => 14928;
use constant ESIS_CLONE_VOL_TRANSITING => 14929;
use constant ESIS_CLONE_STALE_INODE => 14930;
use constant ESIS_CLONE_STALE_DINODE => 14931;
use constant ESIS_CLONE_STALE_RINODE => 14932;
use constant ESIS_CLONE_SHUTDOWN => 14933;
use constant ESIS_CLONE_FAILOVER => 14934;
use constant ESIS_CLONE_CLONE_SFILE_NONEXIST => 14935;
use constant EVOL_NFS_ENABLED => 14936;
use constant ESIS_CLONE_CLONE_DIFF_VOLUME => 14937;
use constant ESIS_CLONE_CLONE_SFILE_ATTR => 14938;
use constant ESIS_CLONE_CLONE_CFILE_ATTR => 14939;
use constant ESIS_CLONE_CLONE_FH => 14940;
use constant ESIS_CLONE_CLONE_SOURCE_FH => 14941;
use constant ESIS_CLONE_CLONE_TYPE_SUPP => 14942;
use constant ESIS_CLONE_NLCSR_INPROG => 14943;
use constant ESIS_CLONE_CLONE_OVERLAP_RANGE => 14945;
use constant ESIS_CLONE_CLONE_INVALID_RANGE => 14946;
use constant ESIS_CLONE_CLONE_INVALID_SOURCE => 14947;
use constant ESIS_CLONE_CLONE_INVALID_CLONE => 14948;
use constant ESIS_CLONE_CLONE_INVALID_DIR => 14949;
use constant ESIS_CLONE_CLONE_WORM_VOL => 14950;
use constant ESIS_CLONE_VDISK_INVALID_NAME => 14951;
use constant ESIS_CLONE_CLONE_EXIST => 14952;
use constant ESIS_CLONE_SFILE_READ => 14953;
use constant ESIS_CLONE_CFILE_WRITE => 14954;
use constant ESIS_CLONE_LICENSE_EXPIRED => 14955;
use constant ESIS_CLONE_NOT_LICENSED => 14956;
use constant EVOL_IN_NVFAILED_STATE => 14957;
use constant EQUOTAS_NO_VALID_RULES => 14958;
use constant EQUOTA_POLICY_NOT_FOUND => 14959;
use constant ESIS_CLONE_DECOMP_ACTIVE => 14960;
use constant ESIS_CLONE_SPLIT_MAP => 14961;
use constant ESIS_CLONE_SOURCE_TOO_SMALL => 14962;
use constant ESIS_CLONE_DOWNGRADE => 14963;
use constant ESIS_CLONE_FLEXCLONE_SPLITTING => 14964;
use constant ESIS_CLONE_CLONE_INVALID_SPC_RSRV => 14965;
use constant ESIS_CLONE_UNKNOWN => 14966;
use constant ESIS_CLONE_MAX_RANGES => 14967;
use constant ESIS_CLONE_MAX_BLKS => 14968;
use constant ESIS_CLONE_CLONE_CFILE_NONEXIST => 14970;
use constant ESNAPMIRROR_NOT_INITIALIZED => 15000;
use constant EAGGR_TOO_LARGE => 15001;
use constant EQTREE_SECURITY_GET_FAILED => 15002;
use constant EQTREE_OPLOCK_GET_FAILED => 15003;
use constant EINTENTLOG_READ_FAILED => 15004;
use constant EOPLOCKS_TOO_MANY_RECALLS_PENDING => 15007;
use constant ESNAPMIRRORSUBSYSTEMNOTINITED => 15008;
use constant EQUOTA_CONTROL_METAFILE_OPEN => 15009;
use constant EQUOTA_CONTROL_METAFILE_READ => 15010;
use constant EMAXFILES_TOO_LARGE => 15011;
use constant ESNAPMIRRORDESTSTATEINVALID => 15012;
use constant EILLEGAL_INODE_CHECK => 15013;
use constant ECOL_COPY_INVALIDINPUTERROR => 15014;
use constant ECOL_COPY_INTERNALERROR => 15015;
use constant ECOL_COPY_FILENOTFOUND => 15016;
use constant ECOL_COPY_NORESOURCES => 15017;
use constant ECOL_COPY_NOACCESSTOSRC => 15018;
use constant ECOL_COPY_VOLOFFLINE => 15019;
use constant ECOL_COPY_DSTREADONLY => 15021;
use constant ECOL_COPY_ISDIRECTORY => 15022;
use constant ECOL_COPY_NOSPACE => 15023;
use constant ECOL_COPY_COPYFAILED => 15024;
use constant ECOL_STATUS_INVALIDINPUTERROR => 15025;
use constant ECOL_STATUS_COPYIDNOTFOUND => 15026;
use constant ECOL_STATUS_INTERNALERROR => 15027;
use constant ECOL_ABORT_INVALIDINPUTERROR => 15029;
use constant ECOL_ABORT_INTERNALERROR => 15030;
use constant ECOL_ABORT_COPYIDNOTFOUND => 15031;
use constant ETELNETSHUTDOWNERROR => 15032;
use constant ECORALSET_ONLINE_FAILED => 15550;
use constant ESTRIPEDVOL_NOT_FULLY_ONLINE => 15551;
use constant EVOL_BAD_VVLABEL_CKSUM => 15600;
use constant EVOL_BAD_VVLABEL_MAGIC => 15601;
use constant EVOL_BAD_VVLABEL_UUID => 15602;
use constant EVOL_BAD_VVLABEL_VERSION => 15603;
use constant EVOL_FAILED_TO_ONLINE => 15604;
use constant EVOL_INCOMPLETE => 15605;
use constant EVOL_MIRROR_TYPE_INVALID => 15606;
use constant EVOL_BAD_MODE_BITS => 15607;
use constant ECOMPRESSING => 15608;
use constant EVOLUMENOTCOMPRESSENABLED => 15609;
use constant ECOMPRESSIONGATHERER => 15610;
use constant ECOMPSHARINGBEYONDLIMIT => 15611;
use constant ECOMPRESSCLONEINPROG => 15612;
use constant EIRON_STREAM_DIR_UPGRADE => 15650;
use constant EIRON_UPGRADE_DISALLOWED => 15651;
use constant EIRON_NOT_RUNNING => 15652;
use constant EIRON_OC_DISALLOWED => 15653;
use constant EIRON_PREV_CP_DISALLOWED => 15654;
use constant EIRON_QTREE_READONLY => 15655;
use constant EIRON_ROOT_AGGR_DISALLOWED => 15656;
use constant EIRON_SCANS_DISALLOWED => 15657;
use constant EIRON_SPARSE_VOL_NOT_ONLINE => 15658;
use constant EIRON_STARTING => 15659;
use constant EIRON_STOP_IN_PROGRESS => 15660;
use constant ESNAPMIRRORTRANSFERFAILED => 15662;
use constant ESNAPMIRRORINVALIDUUID => 15663;
use constant ESNAPMIRRORINVALIDINPUT => 15664;
use constant ESNAPMIRRORNOMEM => 15665;
use constant ESNAPMIRRORNOTSUPPORT => 15666;
use constant ESNAPMIRRORVOLNOTFOUND => 15667;
use constant ESNAPMIRROROPNOTFOUND => 15668;
use constant EQTREE_DOES_NOT_EXIST => 15669;
use constant EQTREE_HAS_SHARES => 15670;
use constant EQTREE_HAS_FILES => 15671;
use constant EQUOTAS_ON => 15672;
use constant EQUOTAS_OFF => 15673;
use constant EOP_DISALLOWED_ON_NOT_HOME_AGGR => 15674;
use constant EOP_DISALLOWED_ON_ROOT_AGGR => 15675;
use constant EOP_DISALLOWED_ON_AGGR_WITH_NODE_VOLS => 15676;
use constant EOP_DISALLOWED_ON_STRIPED_AGGR => 15677;
use constant EINVALID_HA_POLICY => 15678;
use constant ESTAMPREDIRECTSNAPIDERROR => 15679;
use constant EQUOTAS_OPERATION_MISMATCH => 15680;
use constant EVOLUME_OP_NOT_SUPPORTED_BY_OWNER => 15681;
use constant EOP_ERR_MODE_MISMATCH_OBJ_ORIGINALLY_CLUSTERED => 15682;
use constant EOP_ERR_MODE_MISMATCH_OBJ_ORIGINALLY_UNCLUSTERED => 15683;
use constant EOP_CLUSTER_ATTR_DISALLOWED => 15684;
use constant ESNAPMIRRORTRANSFEREXISTS => 15685;
use constant ESNAPMIRRORCHECKMISMATCH => 15686;
use constant ESNAPMIRRORIMAGENOTFOUND => 15687;
use constant ESNAPMIRRORSTREAMNOTFOUND => 15688;
use constant ESNAPMIRRORTRANSFERNOTFOUND => 15689;
use constant ESNAPMIRRORSESSIONNOTFOUND => 15690;
use constant ESNAPMIRRORTRANSFERNOTCOMPLETE => 15691;
use constant ESNAPMIRRORINTERNALERROR => 15692;
use constant ESNAPMIRROROTHER => 15693;
use constant EARRAYNOTFOUND => 15694;
use constant EOP_DISALLOWED_ON_CFO_AGGR => 15695;
use constant EOP_DISALLOWED_ON_SFO_AGGR => 15696;
use constant ENODENOTFOUND => 15697;
use constant EVSERVERNOTFOUND => 15698;
use constant EUSECLUSTERNATIVEUI => 15699;
use constant ESCHEDNOTFOUND => 15700;
use constant EMULTIPLEVOLSFOUND => 15701;
use constant EVERSION_INVALIDRANGE => 15702;
use constant EVERSION_EXISTS => 15703;
use constant ERESOURCEINUSE => 15704;
use constant EVOL_MANIFEST_NOT_AVAILABLE => 15705;
use constant EVOL_MANIFEST_QUERY_NOT_DEFINITIVE => 15706;
use constant EVOL_TRANS_BLOCKING_FEATURES => 15707;
use constant EUNABLE_TO_UPDATE_VOLDB => 15708;
use constant EVOL_UNABLE_TO_SET_UP_SNAPSHOT_XLATE_TABLE => 15709;
use constant EAGGR_SNAPSHOT_IN_PROGRESS => 15710;
use constant EAGGR_HAS_SNAPSHOTS => 15711;
use constant EAGGR_HAS_UNSUPPORTED_VOLUME => 15712;
use constant EAGGR_CANT_UNDO_HYBRID => 15713;
use constant EAGGR_HYBRID => 15714;
use constant EOP_DISALLOWED_ON_SSD_AGGR => 15715;
use constant ENOT_A_AZCS_DISK => 15716;
use constant ENO_AZCS_DISKS => 15717;
use constant EMCS_NOT_ALLOWED_WITH_LUNS => 15718;
use constant EAGGR_ZONED_NOT_ALLOWED_WITH_DISKS => 15719;
use constant ESNAPSHOTRESTOREINPROGRESS => 15801;
use constant ESNAPSHOTTAGSERR => 15802;
use constant ESNAPSHOTINVALIDID => 15803;
use constant ESNAPSHOTTAGSNOSPACE => 15804;
use constant ESNAPSHOTTAGSMETAFILEERR => 15805;
use constant EVOL_NOT_IRON_RESTRICTED => 15850;
use constant EIRON_NOT_OPTCOMMIT => 15851;
use constant EVOL_HAS_REPLICA => 15852;
use constant EDENSE_VOL_COMPRESSED => 15853;
use constant EDENSE_CG_MISMATCH => 15854;
use constant EMULTIPLEOPTSFOUND => 15855;
use constant EVOLUME_64BIT_UPGRADE_MODE_INVALID => 15856;
use constant EAGGR_WOULD_UPGRADE => 15857;
use constant EAGGR_64BIT_UPGRADE_NOT_IN_PROGRESS => 15858;
use constant EAGGR_SIZE_LESS_THAN_16TB => 15859;
use constant EAGGR_64BIT_UPGRADE_ENOSPC => 15860;
use constant EVOLUME_64BIT_UPGRADE_VVOL_ENOSPC => 15861;
use constant EAGGR_64BIT_UPGRADE_RESTRICTED => 15862;
use constant EOP_DISALLOWED_ON_TRAD => 15863;
use constant EVOLUME_ALREADY_64BIT => 15864;
use constant EVOLUME_64BIT_UPGRADE_DISALLOWED => 15865;
use constant EVOLUME_CANT_OBTAIN_VOLREF => 15866;
use constant EVOLUME_64BIT_UPGRADE_KIREETI_NOT_AVAIL => 15867;
use constant EVOLUME_64BIT_UPGRADE_PREQUAL_NOT_AVAIL => 15868;
use constant EVOLUME_64BIT_UPGRADE_ESTIMATE_IN_PROGRESS => 15869;
use constant EONTAPI_VOLTRANS_JOBNOTFOUND => 15870;
use constant EONTAPI_VOLTRANS_LOG_INVALIDOFFSET => 15871;
use constant EONTAPI_VOLTRANS_LOG_REC_NOTFOUND => 15872;
use constant EDENSE_DEDUPE_NOT_DISABLED => 15873;
use constant EDENSE_COMPRESSION_NOT_DISABLED => 15874;
use constant EDENSE_CONCURRENT_LIMIT => 15875;
use constant EAGGR_MIGRATE_CORE => 15876;
use constant ESHUTDOWN_INPROGRESS => 15877;
use constant ENOT_HOMED_TO_PARTNER => 15878;
use constant ENOT_SFO_HA_POLICY => 15879;
use constant EAGGR_FAILED_LIMBO => 15880;
use constant EAGGR_MIGRATE_OFFLINE_FAILED => 15881;
use constant EAGGR_MIGRATING => 15882;
use constant EAGGR_MIGRATE_VETO => 15883;
use constant EDENSE_VOL_NOT_TRANSITIONED => 15884;
use constant ESNAPMIRRORVOLUMENOTQUIESCED => 15885;
use constant ESNAPMIRRORTRANSFERCOMPLETE => 15886;
use constant ESNAPMIRRORCHECKSUMERROR => 15887;
use constant ESNAPMIRRORNETWORKERROR => 15888;
use constant ESNAPMIRRORVOLUMEIDERROR => 15889;
use constant ESNAPMIRRORFILESYSTEMERROR => 15890;
use constant ESNAPMIRRORCHECKERDIFFSNAPSHOTS => 15891;
use constant EOP_DISALLOWED_ON_BUSY_MIRROR => 15892;
use constant EOP_DISALLOWED_ON_LOADSHARING_VOL => 15893;
use constant EOP_DISALLOWED_ON_CLONE_PARENT => 15894;
use constant EOP_DISALLOWED_ON_BACKUP_ACTIVE_VOL => 15895;
use constant EOP_DISALLOWED_ON_STRIPED_VOL => 15896;
use constant EOP_DISALLOWED_ON_COMPRESSED_VOL => 15897;
use constant EOP_DISALLOWED_ON_7MODE_VOL => 15898;
use constant EOP_DISALLOWED_ON_VOL_ALREADY_ON_AGGR => 15899;
use constant ESNAPMIRRORUNDELETEDSNAPSHOTONDEST => 15900;
use constant ESNAPMIRRORENGINETYPENOTSPECIFIED => 15901;
use constant ESNAPMIRRORMISMATCHEDSNAPSHOTLISTS => 15902;
use constant ESNAPMIRRORDESTINATIONNOTRESTRICTED => 15903;
use constant ESNAPMIRRORDESTINATIONNOTEMPTY => 15904;
use constant ESNAPMIRRORNOSNAPLOCKVOLUME => 15905;
use constant ESNAPMIRRORNOCOMPRESSEDVOLUME => 15906;
use constant ESNAPMIRRORDESTVOLTOOSMALL => 15907;
use constant EROOTVOL_NOT_FULLY_GUARANTEED => 15908;
use constant EVOL_FRACTIONAL_RESERVE_INVALID_FOR_ROOT => 15909;
use constant EVOL_FRACTIONAL_RESERVE_INVALID_FOR_PENDING_ROOT => 15910;
use constant EVOL_FRACTIONAL_RESERVE_INVALID_FOR_IRON_ROOT => 15911;
use constant EOP_64BIT_UPGRADE_SCANNER_DISABLED => 15912;
use constant E_ADDRFAMILY => 16000;
use constant E_AGAIN => 16001;
use constant E_BADFLAGS => 16002;
use constant E_FAMILY => 16004;
use constant E_MEMORY => 16005;
use constant E_NODATA => 16006;
use constant E_NONAME => 16007;
use constant E_SERVICE => 16008;
use constant E_SOCKTYPE => 16009;
use constant E_SYSTEM => 16010;
use constant E_BADHINTS => 16011;
use constant E_PROTOCOL => 16012;
use constant E_NXDOMAIN => 16013;
use constant E_RESNULL => 16014;
use constant E_MAX => 16015;
use constant EDISKASSIGNFAIL => 16016;
use constant ENOFMMDEVICES => 16017;
use constant EVFILERMONITORNOTSTARTED => 16018;
use constant EFCMON_GENERATION => 16019;
use constant EFCMON_INVALID_CONFIG => 16020;
use constant EVOLMOVEJOBNOTINCUTOVERDEFERRED => 16021;
use constant EVOLMOVEJOBSIGNALSENDFAILED => 16022;
use constant E_VOL_MOVE_NOT_COMPATIBLE_VERSION => 16023;
use constant E_VOL_MOVE_DC_NOT_ALLOWED => 16024;
use constant E_OP_DISALLOWED_ON_AGGR_NOT_IN_VSERVER_LIST => 16025;
use constant E_OP_UNSUPPORTED_NO_SPACE_ON_DESTINATION_AGGR => 16026;
use constant EROLENOTFOUND => 16031;
use constant EINVALIDAPPLICATION => 16032;
use constant EROLECONFIGNOTFOUND => 16033;
use constant EUSERNOTFOUND => 16034;
use constant EINVALIDACCESS => 16035;
use constant EUSERLOCKFAILED => 16036;
use constant EUSERUNLOCKFAILED => 16037;
use constant ECMDDIRNOTFOUND => 16039;
use constant EINVALIDCMDDIRNAME => 16041;
use constant EINVALIDQUERY => 16042;
use constant EAPPLICATIONNOTFOUND => 16043;
use constant EAUTHENTICATIONMETHODNOTFOUND => 16044;
use constant ESTRIPEDVOL_PRIVILEGELEVEL => 16501;
use constant EVOLUME_DEST_STRIPED_VOL_NAME_NOT_ALLOWED => 16502;
use constant EVOLUME_FLEX_TO_STRIPED_NOT_ALLOWED => 16503;
use constant ECANTQUIESCELASTPATH => 16504;
use constant EINVALIDTARGET => 16505;
use constant ELUNQUIESCING => 16506;
use constant ERESUMEFAILED => 16507;
use constant EQUIESCEFAILED => 16508;
use constant EQUIESCENOTSUPPORTED => 16509;
use constant EONTAPI_VOLTRANS_GOINGHOME => 16510;
use constant EONTAPI_VOLTRANS_VOLNOTFOUND => 16511;
use constant E_DIRECTORY_CHANGED => 16512;
use constant EOP_DISALLOWED_ON_SPARSE_VOL => 16513;
use constant EOP_DISALLOWED_ON_AGGR_WITH_SPARSE_VOL => 16514;
use constant EPARTNERDISKONLY => 16515;
use constant EAGGR_MIGRATE_HA_MSG_ERR => 16516;
use constant EAGGR_MIGRATE_ONLINE_TIMEOUT => 16517;
use constant EAGGR_MIGRATE_ONLINE_FAILED => 16518;
use constant EVOLUMENOTLOCAL => 16600;
use constant EVOLUME_RELSTATUS_UNKNOWN => 16601;
use constant ESNAPMIRRORDBLADEABORT => 16602;
use constant ESNAPMIRRORSCANNINGBLOCKMETADATA => 16603;
use constant ESNAPMIRROR_REF_OR_XFER_SNAPSHOT_DELETED => 16604;
use constant ESNAPMIRRORUNKNOWNFSVERSION => 16605;
use constant ESNAPMIRRORJUMPAHEADFAILED => 16606;
use constant ECKSUMNOTKNOWN => 17000;
use constant ECKSUMTYPEMISMATCH => 17001;
use constant EINVENTORYMISMATCH => 17002;
use constant EPARENTNOTONLINE => 17003;
use constant ESOURCE_ISNOT_LOCAL_VOLUME => 17100;
use constant EDEST_ISNOT_LOCAL_VOLUME => 17101;
use constant ESOURCE_IS_LS_VOLUME => 17102;
use constant ESOURCE_ISNOT_LS_VOLUME => 17103;
use constant ESOURCE_DEST_SAME => 17104;
use constant ESOURCE_IS_DIFFERENT => 17105;
use constant ESOURCE_IS_EXISTING_DEST_VOLUME => 17106;
use constant ESOURCE_VOLUME_HAS_CACHE => 17107;
use constant ESOURCE_ISNOT_RW_VOLUME => 17108;
use constant ESOURCE_IS_STRIPED_VOLUME => 17110;
use constant EDEST_ISNOT_LS_VOLUME => 17111;
use constant EDEST_IS_EXISTING_SOURCE_VOLUME => 17112;
use constant EDEST_IS_EXISTING_DEST_VOLUME => 17113;
use constant EDEST_ISNOT_DP_VOLUME => 17114;
use constant EDEST_IS_RW_VOLUME => 17115;
use constant EDEST_VOLUME_IN_LS_RELATION => 17116;
use constant EDEST_VOLUME_NOT_EMPTY => 17117;
use constant EDEST_VOLUME_HAS_CACHE => 17118;
use constant EDEST_IS_CACHE_VOLUME => 17119;
use constant EDEST_VOLUME_NOT_INITIALIZED => 17120;
use constant EDEST_IS_STRIPED_VOLUME => 17121;
use constant ERELATION_EXISTS => 17122;
use constant ENOSNAPSHOT_COPY => 17123;
use constant EOP_FROM_NONMGR_VSERVER => 17124;
use constant EEMPTY_VOLUMES => 17125;
use constant ESCHEDULE_DOESNT_EXIST => 17126;
use constant ERELATION_NOT_QUIESCED => 17127;
use constant ERELATION_IS_QUIESCED => 17128;
use constant ESOURCE_DEST_VSERVERS_DIFFERENT => 17129;
use constant ENOTRANSFER_IN_PROGRESS => 17130;
use constant EANOTHER_OP_ACTIVE => 17131;
use constant EDEST_LS_VOLUME_CURRENT => 17132;
use constant EDEST_VOLUME_OFFLINE => 17133;
use constant ELS_SET_DEST_VOLUMES_NOT_CURRENT => 17134;
use constant ELS_SET_ISNOT_INITIALIZED => 17135;
use constant ETRIES_COUNT_IS_ZERO => 17136;
use constant ETRANSFER_IN_PROGRESS => 17137;
use constant EDEST_MIRROR_ENGINE_INCOMPATIBLE => 17138;
use constant ENOCHECK_IN_PROGRESS => 17139;
use constant EVOLUMES_WITH_DIFF_STRIPES => 17140;
use constant EFAILOVER => 17141;
use constant EDEST_IS_LS_VOLUME => 17142;
use constant ESIS_CLONE_VFILER_ACCESS => 17143;
use constant ESPARSE_TOO_MANY_SPARSE_VOLS => 17144;
use constant ESPARSE_VOL_CREATE_FAILED => 17145;
use constant ESPARSE_UNKNOWN_PROTOCOL => 17146;
use constant ESPARSE_SRC_VOL_UNAVAILABLE => 17147;
use constant ESPARSE_SRC_VOL_NOT_FLEX => 17148;
use constant ESPARSE_SRC_VOL_WORM => 17149;
use constant EVOL_CLONE_BEING_SPLIT => 17151;
use constant EVOL_MOVING_PARENT_VOL_RETRY => 17152;
use constant EAGGR_READONLY => 17153;
use constant EVOL_LOCKED_SNAPSHOTS => 17154;
use constant EVOL_SCAN_INIT_FAILED => 17155;
use constant EDISKFAILED => 17156;
use constant ESNAPMIRRORCLONERESYNCERROR => 17157;
use constant E_VOLUME_INACCESSIBLE => 17158;
use constant EVOLEXISTS => 17159;
use constant ESNAPMIRROR_JOB_INITIATED_ABORT => 17160;
use constant ESIS_CLONE_CLONE_SUB_COMPRESSION => 17161;
use constant EDEST_IS_VOLUME_CLONE => 17162;
use constant ESIS_CLONE_MAX_DENSE_LIMIT_REACHED => 17163;
use constant ESPARSE_SRC_VOL_INDEX_DIR => 17164;
use constant EDEST_VOL_LOCKED => 18020;
use constant ESRC_VOL_LOCKED => 18021;
use constant EVOLUME_FS_SIZE_FIXED => 18022;
use constant ESNAPMIRRORVMALIGNNOTSUPPORTED => 18023;
use constant EVOLUME_IRON_NON_LOCAL_STATUS => 18024;
use constant EVOLUME_UNSUPPORTED_OPTION_VMALIGN => 18025;
use constant EVOLUME_64BIT_UPGRADE_VVOL_ENOSPC_OVERWRITE => 18026;

1;
